### ISSUE TITLE
Probleme Mime/Type

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#1078]
Lorsque je vais sur
https://nosgestesclimat.fr/simulateur/bilan
j'ai une page quasiment vide. Rien ne semble marcher.
Dans la console javascript, il y a ce message d'erreur:

The stylesheet https://nosgestesclimat.fr/simulateur/publicodes.f5cf4195d1469fd5cef9.css was not loaded because its MIME type, “text/html”, is not “text/css”.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Merci pour le retour. Pouvez-vous nous dire quel navigateur vous utilisez ?

**Comment by nirgal** [comment]
Tor Browser 10.5.2 (based on Mozilla Firefox 78.12.0esr) (64-bit)
Linux 5.10.0-7-amd64

**Comment by nirgal** [comment]
Je peux voir des trucs si je coupe le javascript et que je force l'oppacité de certaines couche à 100% (au lieu de 0% qui n'est pas très lisible!!)

**Comment by nirgal** [comment]
Voir aussi #819

**Comment by JuliePouliquen** [comment]
A priori réglé depuis.
