### ISSUE TITLE
avez-vous tester le questionnaire du site sur Firefox ?

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#1085]
Rien ne s'affiche au première écran... Est-ce temporaire et reproduit ?
v 90.0 (64 bits) sur w10.

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by NansD** [comment]
pas de souci de mon côté

**Comment by JuliePouliquen** [comment]
Je me permets de penser que le problème a depuis été réglé.
