### ISSUE TITLE
Les repas

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#1100]
Bonjour, vous obligez les gens à saisir 14 repas par jour. Hors, il m'arrive régulièrement de ne pas manger le midi par exemple, ou pas le soir.
Il faudrait laisser la possibilité aux gens de saisir le nombre de repas.

Depuis la page : `https://ngc.time-planet.com/documentation/alimentation/déjeuner-et-dîner/par-semaine`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by JuliePouliquen** [comment]
Je dirais qu'il s'agit ici d'UX. Le besoin en calories est assouvi toujours. Peut-être que le repas sauté est compensé par un goûter, par des repas plus costauds avant / après... les 14 sont une façon "classique" de se projeter dans une répartition des types de consommations.

**Comment by Clemog** [comment]
Identifié ici : https://github.com/incubateur-ademe/nosgestesclimat/issues/1841
