### ISSUE TITLE
animal de compagnie

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#1103]
La question possédez-vous des animaux de compagnie ? manque. 
Du coup, j'ai intégré la nourriture à base de viande de mon chat dans mon calcul d'assiette... ça multiplie par 3 mes émissions de GES pour la partie alimentation. 
Ca mériterait une question à part du même style que pour les humains : s'il mange du poisson ou du poulet, ça n'a pas le même impact que du boeuf ou de l'agneau, 100% viande ou 20% viande, ou des graines et autres...

Depuis la page : `https://ngc.time-planet.com/documentation/alimentation`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by JuliePouliquen** [comment]
Cette question est maintenant intégrée pour chat et chien.
