### ISSUE TITLE
Le chauffage de mon logement est collectif

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#1106]
J'habite un immeuble dont le chauffage est collectif, je n'ai pas de facture et le coût est noyé dans les charges. Le questionnaire ne pourrait-il pas dans ce cas mettre un impact carbone moyen, pondéré par la surface de son logement? 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, je ferme au profit de #1645
