### ISSUE TITLE
petit dej

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#1107]
Un mix des 3 solutions : lait/céréales un jour, viennoiseries un autre, rien un autre.. Cela dépend, c'est très variable

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by JuliePouliquen** [comment]
Plus de solutions aujourd'hui, même s'il n'est toujours pas possible de mixer.
