### ISSUE TITLE
Rendement agriculture biologique

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#1111]
Bonjour

     Quand j'ai entendu qu'avec 25% des terres et 20% de l'eau utilisées dans l'agriculture cela fournit 75% de la production alimentaire mondiale (l'agriculture a un rendement 3 fois supérieur à celui de l'agriculture conventionnelle, agriculture conventionnelle qui est moins efficace (inférieur à 1) que la production des chasseurs/cueilleurs de la préhistoire), j'ai dû vérifier tellement la nouvelle est positive :
http://www.changeonsdagriculture.fr/les-rendements-de-l-agriculture-biologique-un-quiproquo-tenace-a117529756
qui fait référence à : http://www.srfood.org/images/stories/pdf/officialreports/20110308_a-hrc-16-49_agroecology_fr.pdf
Ce qui est moins positif, c'est que 10 ans après, ce genre d'information sur la réalité des productions n'est pas connu de tous.
Heureusement, des agriculteurs se rendent compte de cela :
https://www.youtube.com/watch?v=3mvDNxGYfQ0

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by JuliePouliquen** [comment]
Cette source semble contredite par Agribalyse, sur laquelle nous nous basons. Les sources et le raisonnement sont [expliqués ici](https://nosgestesclimat.fr/actions/plus/alimentation/bio)

**Comment by Clemog** [comment]
A relier à https://github.com/incubateur-ademe/nosgestesclimat/issues/1799
