### ISSUE TITLE
Importation 

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#1115]
Sur les questions d'importations et de consommation locale, je comprends que dans les questions ça serait trop complexe pour le grand public mais cela pourrait faire partie des conseils. 
Les émissions d'importations par bateaux ou avions étant loin d'être négligeable. Cela ferait un conseil au moins aussi efficace qu'une partie des conseils déjà présents mais facile à appliquer. 

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by JuliePouliquen** [comment]
Géré aujourd'hui.

**Comment by Clemog** [comment]
Via le local c'est ça @JuliePouliquen ?
je sais pas si une issue existe d'ailleurs pour améliorer ce calcul, ce serait intéressant de s'y repencher

**Comment by JuliePouliquen** [comment]
Ah oui je pensais au local. Il y a peu d'objets sur lesquels nous avons le choix du mode d'importation et je le voyais surtout côté alimentation.
Mais cela pourrait également se relier à une amélioration du modèle avec l'ajout des livraisons ?

**Comment by Clemog** [comment]
Oui effectivement c'est un peu lié
