### ISSUE TITLE
Montant en synthèse diffèrent du montant détaillé

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#1145]
Bonjour et merci pour cet outil !
J’ai peut-être mal lu mais plusieurs fois je ne retrouve pas le même poids de CO2 pour une thématique donnée (ex : transports) dans la page de synthèse et dans la page de détail dédiée, parfois avec des écarts énormes (~ 2 tonnes). Comment cela se fait-il ?

Merci

Depuis la page : `https://nosgestesclimat.fr/documentation/logement`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by JuliePouliquen** [comment]
Au vu de l'ancienneté de cette issue, je me permets de clore, car il est impossible de savoir si c'est encore d'actualité (j'espère que non !).
