### ISSUE TITLE
Est-ce que la consommation de tabac est une source que l’on peut considérer ?

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#135]
Je n’ai vu aucune question sur la consommation de tabac, pourtant l’impact d’une consommation journalière et même hebdomadaire doit être important si l’on regarde la composition, le mode de production, les déchets engendrés, etc.
http://www.journaldelenvironnement.net/article/fumer-nuit-gravement-a-l-environnement,83312

**Comment by laem** [comment]
Très intéressant, merci, à creuser pour voir si l'on peut obtenir un ordre de grandeur assez fiable !

**Comment by Spadice** [comment]
C'est intéressant comme question ^^ En cherchant un peu je suis tombé sur cette étude. (https://pubs.acs.org/doi/abs/10.1021/acs.est.8b01533)
Qui conclue qu'en considérant toute la chaine d'approvisionnement. Une seule cigarette engendre la consommation de 3,7 litres d'eau, 3,5 g d'équivalent pétrole et les émissions de 14 g de CO2eq.

**Comment by laem** [comment]
Très intéressant, merci ! Donc pas grand chose par rapport à nos émissions quotidiennes ...

**Comment by Spadice** [comment]
Oui et non, pour un gros fumeur (1 paquet par jour) on arrive quand même à 100 kgCO2eq/an. C'est pas non plus énorme, mais sur un budget objectif de 2TCO2/an... Ça fait déjà 5%. ^^

**Comment by laem** [comment]
En effet. On peut inclure cette question dans une version du simulateur où on aura déjà amélioré les postes plus essentiels :)

**Comment by laem** [comment]
Autres infos possibles 

---------------

Je pensais ajouter qq question pour les fumeurs puisque
https://www.who.int/fr/news/item/31-05-2022-who-raises-alarm-on-tobacco-industry-environmental-impact

https://www.greenly.earth/blog-fr/quelle-est-l-empreinte-carbone-de-l-industrie-du-tabac#:~:text=Une%20cigarette%20c%27est%20%3A,et%20de%20l%27oxyde%20nitreux.

Ce qui suggère que c'est aussi impactant que la consommation de viande.
