### ISSUE TITLE
Médiane empreinte carbone française

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [incubateur-ademe/nosgestesclimat#1438]
Après un travail de biblio voici les chiffres "disponibles" (que j'ai identifié mais il en manque peut-être) ainsi que les limitations associées.

### Etude [OFCE](https://www.ofce.sciences-po.fr/pdf-articles/actu/carbonevf.jpg.pdf)
_L'empreinte carbone des ménages français et les effets redistributifs d'une fiscalité carbone aux frontières_
Cette étude met en avant une empreinte médiane par ménage de 21,991 tCO2 (Tableau 1). En considérant que les ménages français comportent en moyenne [2,2 personnes](https://www.insee.fr/fr/statistiques/4277630?sommaire=4318291) on obtient une médiane à environ 10 tCO2. Cela me parait énorme (mais dans l’idéal il faudrait aussi une moyenne de la taille des ménages par décile mais je n’ai pas la source). L’explication la plus probable pour ce chiffre « haut » serait que l’étude OFCE se base sur des données anciennes. Elles datent, en effet, de 2011 (EXIOBASE 3, INSEE BdF 2011, SDES-CGDD,) Cependant, l’intérêt de cette source est également de mettre en avant la distribution des émissions de GES pour les ménages et individus sondés en fonction de leur décile (Graphique 4),
![image](https://user-images.githubusercontent.com/66410914/179700218-e89a9745-ac22-41dc-802a-dcc47a57d1ad.png)

### Etude du [World Inequality Report](https://wir2022.wid.world/) 
Cette étude met en avant p194 Table 2. une médiane de 5 tCO2 (c'est très peu). Ce même tableau donne une moyenne à 8, 7 tCO2 ce qui assez proche des 9,3 tCO2 actuels. Peut-on donc faire confiance à ce chiffre de 5 tCO2 ?

### Etude [Chancel & Piketty](http://piketty.pse.ens.fr/files/ChancelPiketty2015.pdf) : 
_Carbon and inequality, from Kyoto to Paris_ 
Cette étude met en avant dans le Table 6. une empreinte de 6,5 tCO2 pour le 3ème décile mais impossible de trouver le détail pour les autres déciles (en source, il est précisé « Authors » et plus loin dans le texte ils précisent avoir repris une source de 2010 qu’ils ont adapté). Leurs données semblent donc anciennes et portent, qui plus est, sur la période  allant de 1998 à 2013.

### Etude du Carbon Consumption Survey 
Je n’arrive pas à mettre la main sur cette étude (si vous avez les données brutes je suis preneur) mais elle a permis de construire le graphe bien connu ci-dessous. Il est mis en avant une médiane de 7 tonnes mais là encore les données datent de 2011...
![image](https://user-images.githubusercontent.com/66410914/179700020-485bce14-d44b-4918-a262-912322d5bf1b.png)

Pour ma part, j'ai souvent entendu le chiffre de 7,2 tCO2 comme valeur médiane. Je pense que ce chiffre vient du Carbon Consumption Survey mais je suis en attente de validation externe.

Par ailleurs, au regard de ces différentes sources il apparait que l’évaluation de la médiane est très variable et souvent basée sur des données anciennes (à l’exception du WIR ?). J’aurais tendance à « plus » faire confiance à ce chiffre car la moyenne donnée est proche des 9,3 tonnes qu’annonce le CGDD et que les données sont plus récentes. 

Bref comme je l'ai dit, je suis en attente de validation externe de mon côté mais si vous avez d'autres à partager @Clemog @laem, n'hésitez pas à les partager car j'en ai peut être loupé

**Comment by laem** [comment]
@Benjamin-Boisserie-ABC n'hésite pas à faire des recherches dans les issues des deux dépôts ou me demander, on avait déjà un travail similaire ici https://github.com/datagir/nosgestesclimat-site/issues/36

Quel est l'objectif d'obtenir une médiane basée sur des facteurs monétaires, c'est-à-dire une méthode très différente ? On a pris la décision de ne plus afficher plus la valeur moyenne en fin de simulation, et surtout, même en obtenant une médiane de confiance, la valeur que nous affichons pendant la simulation est le résultat d'un calcul dynamique qui part d'une sorte de moyenne et termine en valeur personnalisée, de façon continue. 

Même si l'on obtenait une médiane par exemple de 7, je ne vois pas trop ce que ça impliquerait pour nous ?

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, beaucoup de choses se recoupe et j'avais oublié que l'issue #36 existait @laem 

On a en effet décidé de ne plus afficher la moyenne car son "effet" pouvait être contreproductif mais dans ma tête on se réservait la possibilité de mettre en avant la médiane pour faire face au message " oh ca va" des personnes en dessous de la valeur moyenne et orienté ceux en dessous de la médiane vers des actions plus structurelle (à titre perso) et surtout collective (i.e. faire changer les autres). 

Même si en effet, la méthode de calcul à partir de données monétaires et très incertaines c'est un chiffre plus intéressant que la moyenne

**Comment by laem** [comment]
Plus intéressant, je ne sais pas mais complémentaire, très certainement :+1: 

Je pense que si l'on trouve un chiffre d'empreinte médiane digne de confiance, il faut qu'on l'explique bien. Expliquer que ce sont deux méthodes différentes. Ce serait l'occasion d'une belle pédagogie sur ces modes de calcul.

**Comment by JuliePouliquen** [comment]
Je me permets de clôturer au profit de #36 du coup !

**Comment by Clemog** [comment]
Ça ne doit pas être la bonne issue reliée

Pour moi on doit garder cette issue ouverte car très documentée par Benjamin notamment

**Comment by JuliePouliquen** [comment]
Oups il s'agit d'une issue sur le site d'où l'erreur : https://github.com/incubateur-ademe/nosgestesclimat-site/issues/36
