### ISSUE TITLE
Pourquoi une voiture hybride pèse plus qu’une voiture à monteur thermique ? 

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#1452]
Depuis la page : `https://nosgestesclimat.fr/documentation/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
On pourrait faire un paragraphe dans la FAQ pour répondre à cette question :
Voiture thermique, hybride, électrique, quelles différences ?

**Comment by laem** [comment]
Je pense que c'est davantage un sujet pour la documentation. Qu'on l'améliore jusqu'à ce qu'elle devienne explorable. CF aussi les travaux sur l'empreinte de construction vs usage dans monconvertisseurCO2.

**Comment by Clemog** [comment]
Une question va être ajouté dans la FAQ, sur le fond je ferme au profit de https://github.com/incubateur-ademe/nosgestesclimat/issues/1797
