### ISSUE TITLE
TGV vs trains régionaux

### ISSUE THREAD

**Issue by EtienneMassart** [incubateur-ademe/nosgestesclimat#1558]
J'étais très surpris que mes trajets en train aient une empreinte plus grande que ceux en voiture, mais c'est parce que vous utilisez les émissions pour un train moyen (14g/km) et pas pour un TGV (1,7g/km).
Je pense qu'il faudrait implémenter la différence à ce niveau en demandant aux gens quels trains ils prennent le plus.

**Comment by Clemog** [comment]
Merci pour votre remarque ! Aujourd'hui, nous proposons une [moyenne entre les facteurs d'émission TGV et TER](https://github.com/datagir/nosgestesclimat/blob/2ee7ee9776aba4d1ba7f4a356495df3ec4be5a0e/data/transport/transport.yaml#L74)
On pourrait effectivement aller plus loin dans le choix de du train (régionaux ou non, électrifié ou non) mais il n'est pas évident de répondre à cette question... Nous gardons l'issue ouverte, c'est une question intéressante!

**Comment by Benjamin-Boisserie-ABC** [comment]
@JeanAbdel 

Quel est votre cas de figure de vos déplacements en voiture (km, type, nb_passagers, etc.) car même avec un train "moyen" cela me semble bizarre que vous obteniez une empreinte plus faible en voiture

**Comment by JeanAbdel** [comment]
Je ne fais que 2500km/an en voiture avec assez peu de passagers donc j'ai
mis 1.2, mais 30000km par an en train mais essentiellement en TGV ce qui
émet beaucoup moins de CO2 qu'un TER

**Comment by JuliePouliquen** [comment]
Je viens ajouter à cette issue qu'au vu de la formulation, on comprend que l'on doit renseigner ici TER + trains + TGV. Or il faudrait également y mettre a priori le RER et les transiliens, qui ne rentrent dans aucune autre catégorie.

Du côté de la base empreinte, on a : 

- TER traction moyenne : 27,7 gCO2e / passager
   - TER élec : 5,38 gCO2e / passager
   - TER gazole : 63,3 gCO2e / passager 
- RER et transilien : 9,78 gCO2e / passager
   - RER : 5,7 gCO2e / passager
- Train grande ligne : 5,92 gCO2e / passager
- TGV : 2,23 gCO2e / passager

**Comment by mquandalle** [comment]
Actuellement l'empreinte du train est calculée comme étant la moyenne arithmétique de celle du TER et de celle du TGV

https://github.com/incubateur-ademe/nosgestesclimat/blob/11188e80ed6e554cb4ee6da92cd61844780428bd/data/transport/train.publicodes#L8-L17

Autrement dit on considère qu'un passager moyen fait autant de kilomètre en TGV qu'en TER. La note précise que ce choix est fait pour ne pas demander à l'utilisateur de distinguer ses kilomètres en TGV et en TER — ce qui perdrait tout le monde.

Mais alors le choix par défaut devrait être de pondérer par l'usage global de chaque type de train au niveau national. Après une rapide recherche [je trouve ces chiffres](https://www.autorite-transports.fr/wp-content/uploads/2023/06/bilan-ferroviaire-2022-a-mi-2023.pdf) : 

| Type             | Passagers.km (Mds)  | 
|------------------|--------------------|
| SLO  (= TGV ?)            | 61                | 
| TER + Intercités | 22                | 
| RER + Transilien | 17                | 
| Total | 100 |

Donc en multipliant par les données d'empreinte, une empreinte moyenne synthétique du kilomètre de train serait : 

> 61% × 2,23g/km + 22% × 27,7g/km + 17% × 9,78g/km = **9,12g/km**

(par hasard le total fait 100 tout pile donc on peut convertir les valeurs en pourcentage sans calcul en sus)

Alors que le calcul actuel avec la moyenne arithmétique donne (2,23 + 27,7) / 2 = **14,97g/km**, soit 64% de plus que le calcul pondéré selon l'usage national.

**Comment by mquandalle** [comment]
> Je viens ajouter à cette issue qu'au vu de la formulation, on comprend que l'on doit renseigner ici TER + trains + TGV. Or il faudrait également y mettre a priori le RER et les transiliens, qui ne rentrent dans aucune autre catégorie.

Sujet distinct du message ci-dessus mais j'aurais tendance à ne pas inclure les RER / Transilien dans le calcul du train. Quand je répond à la question "combien de km en train sur une année" je n'inclus pas le RER, et si on me demandait explicitement de le faire je n'aurais pas la moindre idée de la valeur à entrer.

Pour moi le sujet RER / Transilien devrait aller avec le metro et être renseigné sous la forme par exemple de "nombre de jours par semaine".

**Comment by JuliePouliquen** [comment]
Très intéressant, merci @mquandalle pour la proposition qui me paraît tout à fait justifiée et que j'aurais tendance à privilégier également si l'on reste dans l'optique de ne pas demander à l'utilisateur de distinguer son usage TGV du reste.

**Comment by Clemog** [comment]
<img width="264" alt="image" src="https://github.com/incubateur-ademe/nosgestesclimat/assets/55186402/4bbdf823-8e9a-4570-90da-77ff8af05b14">
