### ISSUE TITLE
Depreciation function for appliances

### ISSUE THREAD

**Issue by nosgestesclimat** [incubateur-ademe/nosgestesclimat#1589]
Is it included in the calculation when someone only has new appliances due to recent living alone but will still use them until the end of their useful life?
> This ticket was created automatically by our robot from our [contribution page](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Hi, yes the appliances are depreciated on a linear basis. What does it mean ? 

If I bought a new fridge, let's say 100kg of CO2e, we ask you if you usually keep your appliances for a long time, then divide by a factor in years, e.g. 8 years. 

So you only get ~10kg/year for your *new fridge*. This is debatable though. We're using another technique for the new cars. It should be harmonized, but we haven't have time yet do work on this.

**Comment by laem** [comment]
Keeping this issue open, it should be in the FAQ, good point @EmileRolley

**Comment by Clemog** [comment]
Suite à https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1181, je me permets de fermer cette issue :)
