### ISSUE TITLE
Comparaison avec le site Global Carbon Projet

### ISSUE THREAD

**Issue by RafaelMaychmaz** [incubateur-ademe/nosgestesclimat#1612]
Bonjour, un grand merci pour ce simulateur.

Le site [http://www.globalcarbonatlas.org/en/CO2-emissions](http://www.globalcarbonatlas.org/en/CO2-emissions) indique de l'on a en France une moyenne d'émission de de 4t de CO2.

QUESTION : comment expliquer la différence avec les données que l'on trouve sur le simulateur de l'ADEME Nos Gestes Pour Le Climat ? Quelle est l'information fiable ?

Je pose la question car, suite à une question de ma part sur le décret tertiaire, le maire de Saint-Cloud a fait référence au site Global Carbon Project pour indiquer qu'avec 4 t de CO2, la France était déjà exemplaire et que ce n'était pas à nous de faire des efforts. Source : [https://www.youtube.com/watch?v=4Z27sqVx-YY&t=7971s](https://www.youtube.com/watch?v=4Z27sqVx-YY&t=7971s) à 1:48:40.

Merci par avance pour votre éclairage. Sensibiliser les élus locaux est clé pour avancer sur la transition énergétique et écologique.

Cordialement
Rafaël Maychmaz
Conseiller Municipal à Saint-Cloud

**Comment by Benjamin-Boisserie-ABC** [comment]
Bonjour @RafaelMaychmaz,

En parcourant la rubrique méthode du Global Carbon Atlas (GCA), j'ai pu relevé plusieurs différences notables : 
- l'impact de l'agriculture et l'élevage ne semble pas pris en compte (qui représente environ 1/5 de l'empreinte française).
- le GCA limite semble limiter son analyse à la simple combustion des énergies fossiles (gaz, charbon et pétrole), au torchage et aux émissions issus des procédés des industries cimentières. Et même s'il parle d'émission de consommation je ne pense pas que le GCA prenne en compte les émissions des produits et services achetés.

Pour faire simple, je pense que la grande différence s'explique par l'approche territoriale suivie par le GCA, approche limitante qui ne prend pas en compte les émissions importées de notre consommation.

Bref, il est certain que le Global Carbon Atlas sous-estime l'empreinte française et donc la moyenne du "français moyen". Je vous référerai sur l'empreinte française à ce graphe du [Haut Conseil Climat](https://www.hautconseilclimat.fr/wp-content/uploads/2020/10/hcc_rapport_maitriser-lempreinte-carbone-de-la-france-1.pdf) (cf. ci dessous) qui situe l'empreinte française à environ 750 Mt CO2e contre 306 Mt CO2e pour le CGA.
![image](https://user-images.githubusercontent.com/66410914/205867949-56335d2f-2494-4ea9-bae2-7a2a1e21ff77.png)

Quant à l'empreinte moyenne le dernier chiffre du SDES se situe à [8,9t](https://www.statistiques.developpement-durable.gouv.fr/lempreinte-carbone-de-la-france-de-1995-2021) soit plus du double des 4t annoncées par votre maire...

Enfin, sachez que l'Association Bilan Carbone, qui participe au développement de Nos Gestes Climat et qui porte la méthode Bilan Carbone, est tout à fait apte à organiser des sessions de sensibilisation/formation aux enjeux climat et aux problématiques de comptabilité carbone (que ce soit à l'échelle individuelle ou à l'échelle d'une collectivité) pour vos élus. Si cela vous intéresse : n'hésitez pas à nous contacter sur l'adresse contact@abc-transitionbascarbone.fr

**Comment by RafaelMaychmaz** [comment]
Bonjour,
Merci beaucoup pour votre réponse documentée !
Je vais prendre contact.

**Comment by laem** [comment]
Fixed by https://github.com/datagir/nosgestesclimat-site/pull/740
On va mettre une référence à l'article pédagogique dans la FAQ.
