### ISSUE TITLE
Evolution forte des chiffres depuis le mois d'aout 2022 : refonte du mode de calcul ?

### ISSUE THREAD

**Issue by ERIO17** [incubateur-ademe/nosgestesclimat#1616]
## Poser une question 

*J'ai relevé le 1er aout 2022 les chiffres du bilan carbone par personne publiés sur le site https://nosgestesclimat.fr/documentation/bilan et je constate aujourd'hui une explosion des chiffres. Que s'est il passé ? un changement/amélioration du mode de calcul ? un oubli ? des nouvelles données ? l'impact de la guerre en ukraine ?  :
-  1er aout 2022  :      Valeur : 5 391,9 kgCO2e / personnes  dont 
-                                  Logement  55,77 kgCO2e / personnes
-                                  Transport                                2 176,82 kgCO2e
-                                  Alimentation                           1 704,24 kgCO2e
-                                  Numérique                              96,07 kgCO₂e / an
-                                  Divers                                     246 kgCO2e
-                                  Services publics                      1 113 kgCO2e
-  6 décembre 2022 : Valeur : 7 852,65 kgCO2e / personnes*
-                                  Logement                            1 412,48 kgCO2e / personnes
-                                  Transport                             2 444,45 kgCO2e
-                                  Alimentation                         2 033,74 kgCO2e
-                                  Numérique                            212,16 kgCO2e
-                                  Divers                                   636,82 kgCO2e
-                                  Services publics                    1 113 kgCO2e
## Proposer une amélioration 
Si les derniers chiffres s'avèrent corrects, une mention précisant les raisons du changement et un historique permettraient une meilleure appréhension du problème.
Merci d'avance pour tout éclaircissement.
Cdt
Jean-Luc Giboire
*Si vous avez une idée précise de votre amélioration, vous pouvez directement suivre [ce guide de contribution](https://github.com/datagir/nosgestesclimat/blob/master/CONTRIBUTING.md)*

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by Benjamin-Boisserie-ABC** [comment]
Bonjour @ERIO17,

Voici une première piste de réflexions quant aux différences que vous observez.

Sachez que le modèle de calcul évolue en continue pour assurer la mise à jour de l'outil et le développement de nouvelles fonctionnalités et actes de consommation pris en compte. Cependant, ces dernières ne sont pas censées induire une explosion de la valeur de l'empreinte.

Dans votre comparaison, la valeur de 55 kgCO2e pour le poste logement m'interpelle fortement et je pense peut être qu'il y a eu une différence de saisie entre votre première simulation et la seconde. Quelles données avez-vous renseigné sur ce poste ?

Pour les autres postes : 
- les FE alimentation ont été mis à jour avec les nouvelles données Agribalyse. Cela explique certainement la légère augmentation de ce poste dans votre simulation
- le poste logement a également été mis à jour mais cela impact (à la baisse) surtout les utilisateurs répondant "je ne sais pas" aux questions.

Quant aux autres postes, je ne vois pas ce qui, depuis août dernier, a puis induire de telles augmentations notamment sur les postes numériques et divers.

**Comment by JuliePouliquen** [comment]
Je me permets de clore cette issue.
