### ISSUE TITLE
Ajout du ski [Note : 7/10]

### ISSUE THREAD

**Issue by mquandalle** [incubateur-ademe/nosgestesclimat#1693]
## Note : [(3 + 3 + 1) = 7/10](https://github.com/incubateur-ademe/nosgestesclimat/blob/master/PRIORISATION.md)

Question de saison, quel est l'impact carbone d'une journée de ski ?

D'après [cette étude](https://www.mairie-tignes.fr/cms_viewFile.php?idtf=71518&path=guide-sectoriel-montagne.pdf) commandée par Tignes, La Clusaz et le Grand Bornand c'est 48,9 kgCo2eq/jour :

![image](https://user-images.githubusercontent.com/1730702/214679023-a8e5cd64-0bfc-427b-8df1-7932420d779f.png)

Mais on voit que si on intègre ce chiffre directement, on fait du double comptage sur plusieurs postes, en particulier le transport domicile-station qui représente plus de la moitié de l'impact calculé. De même pour l'alimentation, déjà prise en compte via les autres questions.

Pour l'équipement ce n'est pas encore pris en compte mais on peut considérer que c'est un sujet séparé #1316.

Reste l'entretien du domaine (dameuses au gazole), les infrastructures (remontées mécaniques), et le logement de tourisme (connexe #1674). D'après cette infographie on obtient 1,4 kg + 7,9 kg + 1,7 kg = 11 kg/jour de ski

**Comment by Benjamin-Boisserie-ABC** [comment]
Merci pour l'étude qui semble très intéressante !

Cela me fait réfléchir à la création éventuelle d'une rubrique "Loisirs" élargie dans laquelle on pourrait trouver (liste non-exhaustive) le ski, les achats d'articles de sport, d'éventuels loisirs plus ou moins carbonés (sports mécaniques, voile, etc.), la consommation d’hôtellerie et d'événements/sortie culturelle/sportives. 

Cependant, cela veut dire beaucoup d'autres questions, ce qui n'est pas idéal qui plus est quand on sait que certains de ces loisirs seront "de niche" (le ski c'est moins d'un français sur 10, probablement pareil pour les sports mécaniques, etc.) et parfois pour des empreintes carbones faibles. Comme évoqué avec @lbranaa c'est un sujet de discussion à avoir je pense.
