### ISSUE TITLE
Amélioration question produits manufacturés neufs

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat#1703]
Plusieurs problèmes identifiés avec la question "Combien dépensez-vous par an en produits manufacturés neufs (mobilier, livres, etc.) ?" :
- Difficile d'y répondre pour l'utilisateur (par exemple, difficile de savoir tout ce qui doit rentrer dedans, et le périmètre d'exclusion des questions à venir n'est pas forcément clair)
- Mélange de produits très différents (livres, mobilier)
- Utilisation d'un facteur monétaire (prix pas forcément représentatif du poids carbone)

Idées à investiguer : 
- Sortir des gros éléments avec d'autres questions (ex : mobilier) ? -> Done ✅
- Utile de garder cette question ou à supprimer ?
- Préciser la question ?

A lier à #1695 

Pour info, nos partenaires suisses nous ont également fait ces mêmes retours sur cette question, en proposant : 
- Diviser les catégories ?
- Ajouter des catégories ?

[EDIT 09/03/23]

Suite à la mise en ligne de #1700, cette question a été largement améliorée mais il reste de nombreux questionnements, notamment sur l'utilisation d'un ratio monétaire.

A investiguer:

- [ ] Etudier les possibilité de diviser le contenu
- [ ] De considérer certaines dépenses comme un "minimum" ?
- [ ] Utiliser les chiffres de l'inventaire du CITEPA/SDES ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Je lie à la PR #1700 qui propose un modèle d'évaluation GES des biens d'ameublement calqué sur les mosaïques électroménager, numérique et vêtements

**Comment by Clemog** [comment]
J'ai commencé un premier travail sur la refonte de cette question dans #1700
