### ISSUE TITLE
Ajouter une carte action "Découvrez l'impact des gestes & objets sur le climat" pour renvoyer sur ICO2

### ISSUE THREAD

**Issue by Clem-mrtn** [incubateur-ademe/nosgestesclimat#1756]
Ce n'est pas désintéressé comme démarche, mais je me demandais si ce n'était pas intéressant de créé plus de pont entre Impact CO2 et NGC et je me disais que le site aurait pu avoir sa place sur une carte action pour commencer :) 

Les cartes sont aujourd'hui classifiées donc on pourrait soit avoir : 
- Dans la partie **Action d'engagement** une carte "Sensibilisez-vous à l'impact des objets et des gestes de votre quotidien sur le climat" qui renverrait sur le site ICO2
- Ou alors **plusieurs cartes actions** thématisée qui renverraient vers des simulateurs spécifiques du site comme l'impact du transport, des usages numériques etc. 

**Qu'en pensez-vous ? Est-ce que ces cartes "Actions d'engagement" sont souvent cliquées ?** 

Aujourd'hui, il me semble qu'ICO2 est mentionné uniquement dans la FAQ : 
<img width="1288" alt="Capture d’écran 2023-03-02 à 16 26 34" src="https://user-images.githubusercontent.com/76995768/222472418-7b02050f-22eb-4dcb-929c-9e77dcdce785.png">

**Comment by laem** [comment]
Ce serait une nouvelle carte ici donc : ![image](https://user-images.githubusercontent.com/1177762/223076132-e28b9334-d83c-4a36-8f56-3cffff5d67f9.png)

Bonne idée je pense. 

Par contre les titres d'action doivent être courts. On pourrait mettre "Aller plus loin dans les chiffres CO2" ? 

Pour les clics, il faut distinguer sélection de l'action (coche :heavy_check_mark: ) et clic. Peu de clics sur ces actions non chiffrées. 

Ici pour le 1er mars. 

![image](https://user-images.githubusercontent.com/1177762/223076805-0b632f95-d41b-4708-ac9d-80662e3090e0.png)

**Comment by laem** [comment]
Par contre, un nombre significatif de sélection 
![image](https://user-images.githubusercontent.com/1177762/223076913-a94dd1d7-9058-4c05-87b8-11128b2f2f84.png)

**Comment by laem** [comment]
Pour revenir à l'intégration de impactCO2, je me dis que c'est aussi (et surtout ?) au cours du test (ou juste à la fin, proposer un parcours expert numérique par exemple) qu'il faudrait permettre d'aller plus loin. 

Parce que sur l'étape action, théoriquement, dans le modèle actuel de parcours, l'utilisateur s'attend à des solutions, plus que de l'évaluation d'empreinte.

**Comment by Benjamin-Boisserie-ABC** [comment]
Je pense que c'est une bonne idée que NGC redirige vers d'autres ressources. Je parlerai en revanche plutôt de la connaissance des ordres de grandeur que "Sensibilisez-vous à l'impact des objets et des gestes"

De manière générale, est-ce que c'est pas un des objectifs du futur volet Action de pousser vers d'autres ressources et acteurs complémentaires de NGC. (ICO2, applications, associations, etc.).

**Comment by Clem-mrtn** [comment]
En effet @lbranaa, je pense que ça n'est plus pertinent d'avoir une carte action citoyenne qui renvoie vers Impact CO2 ! 
Plutôt se concentrer sur comment vous pouvez réutiliser nos ressources dans les questions du quizz :)

**Comment by lbranaa** [comment]
Ok merci ! Je ferme donc l'issue
