### ISSUE TITLE
Facteur d'émission berline hybride sous-estimé ?

### ISSUE THREAD

**Issue by Nerual1999** [incubateur-ademe/nosgestesclimat#1797]
> ⚠️ Avant de créer une issue, lisez attentivement [notre FAQ](https://nosgestesclimat.fr/contribuer) qui explicite un bon nombre des limites du test nosgestesclimat.fr.

Pourquoi est-ce qu'un SUV hybride coûte 6900 en amortissement contre 9600 pour le véhicule en taille moyenne ? Comme le plus gros véhicule a le plus faible coût d'amortissement. 

*Décrivez ici le problème que vous avez eu, l'amélioration que vous souhaitez proposer, ou toute autre question ici.*

## Proposer une amélioration 

*Si vous avez une idée précise de votre amélioration, vous pouvez directement suivre [ce guide de contribution](https://github.com/datagir/nosgestesclimat/blob/master/CONTRIBUTING.md)*

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by Clemog** [comment]
Bonjour @Nerual1999,


Merci pour votre retour, je me suis permis de renommer votre issue.

Effectivement, le facteur d'émission de la partie construction + fin de vie de la berline hybride est inférieur à celui de la citadine hybride. Nos chiffres sont tirés de cette étude : https://europeanclimate.org/wp-content/uploads/2019/11/quelle-contribution-du-vehicule-electrique-a-la-transition-ecologique-en-france.pdf
Nous avons également été surpris comme nous le notons ici : 

https://github.com/datagir/nosgestesclimat/blob/58dc61b5fce748b5aeb70fe7e756deb8e900e87d/data/transport/transport%20.%20voiture.yaml#L366-L380

N'hésitez pas si vous avez des pistes pour nous aider !

**Comment by JuliePouliquen** [comment]
À relier à #1452

**Comment by Clemog** [comment]
Suite à https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1181, je me permets de fermer cette issue :)
