### ISSUE TITLE
Translation bug for `suggestions` from `mosaïque`

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat#1845]
When creating a new `mosaïque` rule, translation script breaks due to `suggestion`

**Comment by lbranaa** [comment]
Je n'ai pas compris @Clemog

**Comment by Clemog** [comment]
C'est un pb au niveau des scripts de traduction de mémoire dans le cas ou on a une règle qui est une mosaïque avec des suggestions

**Comment by jeannelf** [comment]
toujours d'actu?

**Comment by EmileRolley** [comment]
Pas sûr.. Je pense que l'on peut fermer et on ouvrira une nouvelle si le problème apparaît de nouveau.

**Comment by Clemog** [comment]
Je crois que j'avais toujours le souci mais je rouvrirai une carte plus précise quand je l'aurai
