### ISSUE TITLE
Réflexion voiture électrique 

### ISSUE THREAD

**Issue by margauxcoco** [incubateur-ademe/nosgestesclimat#1878]
Retour utilisateur reçu par mail : 
1) Dans un premier temps, j'ai utilisé votre calculateur pour ma propre empreinte carbone. Je viens de changer de véhicule pour passer à l'électrique. J'ai été surpris de prime abord par le fait de perdre 3 tonnes de CO2 en possédant un véhicule électrique de 6 m d'âge (perte = 0 pour 5 ans). Je me suis dit « les acheteurs potentiels de véhicules électriques sont plutôt sensible à l'empreinte carbone et donc, aucun n'aura envie d'acheter un véhicule électrique à ce tarif là, sauf éventuellement une occasion de plus de cinq ans ; et à la vitesse où évolue cette technologie, ce n'est pas demain la veille qu'un acheteur informé et raisonnable va franchir le pas pour une occasion de 5 ans. Conséquence : on n'est pas près d'alimenter le marché de l'occasion pour dans cinq ans... : cela s'appelle un dead-lock, un verrou mortel. ».

2) Par ailleurs, les chiffres de l'Ademe montrent que en moyenne, un véhicule électrique amortit son surcoût de production CO2 en environ 50 000 km. Soit 5 ans à 10 000 km par an. C'est cohérent par rapport aux résultats ci-dessus.

3) Après avoir analysé vos algorithmes j'ai compris l'origine du problème : le surcoût CO2 de la production des véhicules électriques par rapport au thermique. Vous appliquez brutalement l'algorithme, ce qui mène aux constats ci-dessus. Soit. C'est «légal », mais est-ce pour autant « légitime » pour reprendre les termes d'un débat très actuel ?

4) Et donc la question me taraude toujours : comment trancher le noeud gordien du surcoût initial pour rendre l'achat d'un véhicule électrique vertueux, créer le marché futur de l'occasion pour en favoriser l'accès aux moins riches ? En gros comment faciliter la transition du thermique à l'électrique. Le simulateur de l'Ademe peut-il y contribuer ?

5) Tentative :

- on garde l'hypothèse qu'un véhicule thermique ou électriquement la même durée de vie (ex : 15 ans).
- Utiliser comme en finances, la Valeur Nominale d'un titre qu'on possède (la voiture) qui ne verse ses intérêts (Tco2 émis) qu'à l'échéance (ex : 15 ans). Rappel : la valeur nominale est la valeur initiale du titre plus les intérêts à l'échéance.
- Ainsi, la valeur nominale en Tco2 d'un véhicule électrique sera bien inférieure à la valeur nominale d'un véhicule thermique sur sa durée de vie et c'est la réalité. Obtenir la Valeur Nominale CO2 / km
- Utiliser cette valeur nominale pour avoir la contribution dans le bilan carbone individuel annuel en fonction des kilomètres parcourus. Voir exemple attaché.
- L'âge du véhicule n'interviennent plus car il a été prise en compte dans la valeur nominale.
- Ainsi l'acheteur d'un véhicule électrique neuf contribuera immédiatement à la réduction des fossiles et à la création du marché futur de l'occasion. Son investissement dû au surcoût actuel important de la technologie électrique non encore mature paye et est récompensé dans son bilan carbone. Objectif atteint.

Ai-je fait une erreur ? Je serai heureux d'avoir vos commentaires.

Par ailleurs, le lien vers les bilans GES de l'Ademe ne fonctionne pas [[sur cette page](https://nosgestesclimat.fr/documentation/transport/voiture/%C3%A9lectrique/empreinte-au-kilom%C3%A8tre)](https://nosgestesclimat.fr/documentation/transport/voiture/%C3%A9lectrique/empreinte-au-kilom%C3%A8tre) (au moins).

**Comment by maxinesabater** [comment]
Food for Thought 👍 Je complète cette issue par un retour utilisateur ICO2 reçu de la part du Réveilleur (média) : 

Bonjour,

Je pense qu'il y a une erreur d'estimation sur la voiture thermique dans votre outil en ligne https://impactco2.fr/transport . Dans les transports, on voit un rapport légèrement supérieur à 2 entre la voiture électrique et la voiture thermique.

Quand on regarde dans les détails, on voit qu'à la production une voiture électrique émet 3,27 (83,6/25,6) fois plus de CO2/km qu'une voiture thermique !!!

Je connais un peu la littérature scientifique sur le sujet (voir le récent article d'Aurélien Bigo que vous connaissez peut-être https://bonpote.com/la-voiture-electrique-solution-ideale-pour-le-climat/ ) et ce rapport entre les impacts à la production de la voiture électrique et de la voiture thermique, c'est vraiment du jamais vu pour moi !

Vous vous basez sur une étude très limitée ( https://www.ifpenergiesnouvelles.fr/sites/ifpen.fr/files/inline-images/NEWSROOM/Communiqu%C3%A9s%20de%20presse/projet-e4t-bilan-impact-electrification-2018.pdf ), je pense qu'on pourrait trouver mieux, voir le petit état de l'art d'Aurélien Bigo donné plus haut.

J'ai pas mal bossé le sujet personnellement, si vous voulez en discuter plus directement, n'hésitez pas à me contacter, je suis dispo pour en discuter.

Dans l'attente de votre retour,
Rodolphe Meyer.

**Comment by Clemog** [comment]
Merci @margauxcoco ! Je n'ai pas encore pris le temps de lire ses réflexions, ce sera précieux lorsque l'on se repenchera suer le modèle de la voiture !

@maxinesabater je ne suis pas sur que le retour soit lié à cette issue : NGC et ICO2 n'utilisent pas les même données pour le transport et il me semble que l'utilisation de certains FE relevaient de discussions avec le service Transport de l'ADEME notamment (à voir avec Martin, Florian et Clémence)
