### ISSUE TITLE
[Transport] Scission du parcours en deux grandes sous-parties : le quotidien, les vacances

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat#1917]
L'idée ici est de proposer une version de la catégorie "Transport" via une approche "motif" et non par mode de transport pour avoir une autre vision du parcours différente

Dans ce MVP, l'idée est de garder l'UI actuel : les 4 propositions seront les suggestions dans la mesure du possible pour avoir une première version rapidement. Qu'en pensez-vous @JuliePouliquen et @jeremiecook @lbranaa ?

## TO DO

- [ ] Création d'une mosaïque d'entrée pour chacune des deux sous-parties : "quels types de transport utilisez-vous au quotidien / pour vos vacances ?"
- [ ] Un excalidraw pour visualiser l'arbre de décision ? Est-ce nécessaire ?

## Questions qu'il faudra arbitrer

- [ ]  Que se passe t-il si je ne coche pas voiture dans quotidien ? (à ce jour, on pose quand même les questions sur la voiture qu'on utilise)
- [ ]  Où place t-on les modes doux / efficaces ? Des deux côtés ?
- [ ]  Est-ce qu'on en profite pour affiner nos questions sur le train (quotidien => TER / Intercités et vacances => TGV) ?
- [ ] Doit-on différencier la voiture vacances et quotidien ?
- [ ] Combien de semaines de vacances par an ?

Actions actuelles à modifier : 

- [ ] Covoiturage => Scinder boulot et longue distance ? Ce qui pourrait revenir à scinder entre "quotidien" et "vacances"
- [ ] Aller au travail autrement qu'en voiture => Restreindre au périmètre "quotidien"
- [ ] Se passer de voiture pour moins de 5 km => Restreindre au périmètre "quotidien"

**Comment by JuliePouliquen** [comment]
Curieuse de vos retours @Clemog et @jeremiecook

**Comment by JuliePouliquen** [comment]
> Dans ce MVP, l'idée est de garder l'UI actuel : les 4 propositions seront les suggestions dans la mesure du possible pour avoir une première version rapidement. Qu'en pensez-vous @JuliePouliquen et @jeremiecook @lbranaa ?

Totalement raccord avec ça.

**Comment by JuliePouliquen** [comment]
J'ai ajouté au commentaire on top la question du nombre de semaines de vacances. L'idée : pour moi du côté du quotidien on demande une moyenne de prise de transport à la semaine, à multiplier par le nombre de semaines travaillées par an. 
Par défaut, on peut se dire que les gens prennent 5 semaines de vacances par an, mais ça pourrait être une question. Si elle est posée, elle peut également avoir un intérêt côté logement...

**Comment by JuliePouliquen** [comment]
À modifier suite aux dernières discussions avec Jérémie. Cf #1951

**Comment by jeannelf** [comment]
je dois tester quoi ici @Clemog @JuliePouliquen  ?

**Comment by JuliePouliquen** [comment]
> je dois tester quoi ici @Clemog @JuliePouliquen ?

Oups @jeannelf j'aurais pas dû "close as completed" c'est close parce que c'est en doublon ailleurs et mieux expliqué sur la carte #1951
