### ISSUE TITLE
Faire le test en groupe 

### ISSUE THREAD

**Issue by nosgestesclimat** [incubateur-ademe/nosgestesclimat#1938]
Bonjour, 
nous aimerions faire le test en groupe (environ 20taine de personnes) mais l'outil ne reprend pas en compte les nouvelles participations ni les personnes connectées
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Bonjour, 

Avez-vous choisi le mode sondage ou bien le mode conférence ? 

Je crains que vous ne puissiez pas répondre car l'issue a été générée automatiquement, n'hésitez pas à nous recontacter par mail si le problème persiste.
