### ISSUE TITLE
Alimentation - Questionnement autour du bio

### ISSUE THREAD

**Issue by margauxcoco** [incubateur-ademe/nosgestesclimat#1940]
Retour mail contact :
Bonjour L’équipe Nos gestes climat,

Très bien votre réponse automatique et polie mais votre simulateur continue ses dégâts autour de l'alimentation. Je vais bientôt rencontrer Sarah Martin et je compte bien lui demander comment elle a pu valider cela.
Je suis toujours disponible pour vous rencontrer pour travailler cette question de l'alimentation en lien avec une agriculture performante pour l'avenir de l’humanité sur notre planète.

Je fais régulièrement des conférences pour expliquer en quoi vos affirmation contre le bio et la viande sont fausses et surtout quels sont les intérêts financiers qui les diffusent.

Bien cordialement

Gilles Guellier
Anne Martin et Gilles Guellier
15 rue des ormeaux
41120 Cellettes
02 54 44 13 65 et 06 27 53 74 46

**Comment by JuliePouliquen** [comment]
Je me permets de clore au profit de #1799
