### ISSUE TITLE
MAJ FAQ

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat#1943]
Corrigera une partie de https://github.com/incubateur-ademe/nosgestesclimat-site/issues/793

- [ ] Faire une relecture de la FAQ :
   - [ ] Mettre à jour les questions dont la réponse est obsolète
   - [ ] Lister, puis ajouter des questions qui semblent manquer : https://github.com/incubateur-ademe/nosgestesclimat/issues/1625 ; https://github.com/incubateur-ademe/nosgestesclimat/issues/1589 ; https://github.com/incubateur-ademe/nosgestesclimat/issues/1452; https://github.com/incubateur-ademe/nosgestesclimat/issues/88 ; https://github.com/incubateur-ademe/nosgestesclimat/issues/690
- [ ] Proposer un protocole de MAJ de la FAQ (tous les combiens ? par qui ?)
- [ ] Voir si le design de la FAQ mérite d'être revu (possibilité de renvoyer vers une réponse précise, par exemple ?)

**Comment by JuliePouliquen** [comment]
J'ai mis inférieur à 1 jour mais cela peut dépendre de la quantité de choses à réécrire.

**Comment by Clemog** [comment]
J'ai plutôt mis 3 jours ;)
