### ISSUE TITLE
Vous me faites chier

### ISSUE THREAD

**Issue by nosgestesclimat** [incubateur-ademe/nosgestesclimat#1955]
Vous me faites chier
> Depuis la page: `https://nosgestesclimat.fr/simulateur/bilan?question=alimentation.boisson.chaude`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by JuliePouliquen** [comment]
Sans plus de détails, je me permets de clôturer.
