### ISSUE TITLE
double comptage epargne en banque et consommation !!

### ISSUE THREAD

**Issue by wormsf** [incubateur-ademe/nosgestesclimat#1961]
Je réagis à votre assertion dans vos FAQ
**Pourquoi ne pas prendre en compte l'épargne individuelle ?**
Votre Réponse : _Cela ferait une double comptage_
Cette réponse est étonnante, 
Cela voudrait dire qu'une personne qui a 10 000€ à la BNP a la même empreinte carbone que celle qui à la même somme au Crédit coopératif, à la Banque postale ou à la Nef, (même s'ils ont les mêmes habitudes de consommation) 
Cette réponse est d'autant plus étonnante que des calculateurs existent : comme celui d'[OXFAM](https://www.oxfamfrance.org/climat-et-energie/calculez-lempreinte-carbone-de-votre-compte-bancaire/)

- 10000 € à la BNP = 6 tonnes/an
- 10000 € à la Banque Postale = 3,5 tonnes/an
Cordialement

**Comment by JuliePouliquen** [comment]
Bonjour !

Cette question de l'empreinte de l'épargne est complexe à plusieurs niveaux : 

- Tout d'abord pour cette question de la double empreinte : en effet l'épargne mise en banque sert à produire in fine de la consommation, qui est elle comptabilisée dans Nos Gestes Climat. Si l'on comptabilise l'empreinte de l'épargne + celle de la consommation, il y a bien une double comptabilité.
- Et en même temps... Nos Gestes Climat a une vocation pédagogique avant tout et c'est dommage de ne pas diffuser de message quant à l'empreinte des épargnes des citoyens.
- Par ailleurs, la deuxième grosse source de complexité vient du calcul de cette empreinte, qui est loin de faire consensus. 

Nous essayons d'avancer là-dessus ! Pour plus d'infos, n'hésitez pas à lire et contribuer ici : https://github.com/incubateur-ademe/nosgestesclimat/issues/1823

**Comment by Clemog** [comment]
Suite à https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1181, je me permets de fermer cette issue :)
