### ISSUE TITLE
nouvelle question - la cigarette

### ISSUE THREAD

**Issue by thaislbr** [incubateur-ademe/nosgestesclimat#1964]
Bonjour, 

Etant donné la quantité d'eau et de ressources et les matériaux nécessaires pour la conception des produits, pourquoi ne pas rajouter le nombre de cigarettes ou paquets de cigarettes consommés par jour/semaine. 
La question est ce que vous les jetez à la poubelle est-elle pertinente également ?

**Comment by Clemog** [comment]
Bonjour,

Merci pour votre retour, l'ajout de la cigarette est un sujet identifié : #135 

Pour la question des déchets c'est une question qui est importante pour la pédagogie avant tout. L'empreinte des déchets reste non négligeable, je vous invite à jeter un oeil au détail du calcul : https://nosgestesclimat.fr/documentation/alimentation/déchets

Belle journée :)

**Comment by Clemog** [comment]
Je me permets de fermer l'issue mais n'hésitez pas à nous répondre ici si vous avez d'autres questions !
