### ISSUE TITLE
pas d'icone "suivant" sur la page "mode de chauffage, cuisson..."

### ISSUE THREAD

**Issue by nosgestesclimat** [incubateur-ademe/nosgestesclimat#1973]
> Depuis la page: `https://nosgestesclimat.fr/simulateur/bilan?question=logement.chauffage`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contact).

**Comment by EmileRolley** [comment]
Fixed by https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1216
