### ISSUE TITLE
pas d'icone "suivant" sur la page "quels ecogestes..."

### ISSUE THREAD

**Issue by nosgestesclimat** [incubateur-ademe/nosgestesclimat#1974]
> Depuis la page: `https://nosgestesclimat.fr/simulateur/bilan?question=alimentation.déchets.gestes`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contact).

**Comment by EmileRolley** [comment]
Fixed by https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1216
