### ISSUE TITLE
bouton suivant n'apparait pas toujours !

### ISSUE THREAD

**Issue by nosgestesclimat** [incubateur-ademe/nosgestesclimat#1975]
Testé sur chrome et edge, sur certaines questions (liées aux sources de chauffage, aux animaux par exemple, le bouton n'apparait pas et les résultats ne sont pas pris en compte en cliquant sur le lien "je ne sais pas"
> Depuis la page: `https://nosgestesclimat.fr/simulateur/bilan?question=logement.chauffage`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contact).

**Comment by EmileRolley** [comment]
Fixed by https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1216
