### ISSUE TITLE
Pas de prise en compte type énergie 

### ISSUE THREAD

**Issue by nosgestesclimat** [incubateur-ademe/nosgestesclimat#1980]
Bonjour
Pour l'électricité il n'est pas pris en compte le type d'énergie, en effet nous sommes chez enercoop, notre électricite est 100% renouvelable 
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contact).

**Comment by Clemog** [comment]
Bonjour, merci pour votre retour ! Nous y répondons dans notre [FAQ](https://nosgestesclimat.fr/questions-frequentes#électricité-dite-verte) :)
