### ISSUE TITLE
Simulateur gestes du climat en groupe

### ISSUE THREAD

**Issue by Fatth** [incubateur-ademe/nosgestesclimat#1998]
> ⚠️ Avant de créer une issue, lisez attentivement [notre FAQ](https://nosgestesclimat.fr/questions-frequentes) qui explicite un bon nombre des limites du test nosgestesclimat.fr.

## Poser une question

_Bonjour, combien de personnes peut comprendre la simulation "Nos gestes climats en groupe". Merci
Décrivez ici le problème que vous avez eu, l'amélioration que vous souhaitez proposer, ou toute autre question ici._

## Proposer une amélioration

_Si vous avez une idée précise de votre amélioration, vous pouvez directement suivre [ce guide de contribution](https://github.com/datagir/nosgestesclimat/blob/master/CONTRIBUTING.md)_

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by Fatth** [comment]
Bonjour, je me permets de vous reposer la même question.
Dans sa version "groupe", combien le simulateur "nos gestes climats" peut-il accueillir de personnes en simultanée: 10, 20, 100, 200? ...
Merci beaucoup
Thomas Fabri

**Comment by Clemog** [comment]
Bonjour, merci pour votre message ! 
Oui le mode groupe fonctionne correctement pour ce type de groupe :)

Bonne journée !

**Comment by Fatth** [comment]
Merci
Thomas

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Clément ***@***.***>
Envoyé : Monday, July 24, 2023 4:44:24 PM
À : incubateur-ademe/nosgestesclimat ***@***.***>
Cc : Fatth ***@***.***>; Author ***@***.***>
Objet : Re: [incubateur-ademe/nosgestesclimat] Simulateur gestes du climat en groupe (Issue #1998)


Bonjour, merci pour votre message !
Oui le mode groupe fonctionne correctement pour ce type de groupe :)

Bonne journée !
