### ISSUE TITLE
Pourquoi ne pas prendre en compte les enfants à charge ?

### ISSUE THREAD

**Issue by nosgestesclimat** [incubateur-ademe/nosgestesclimat#2007]
Faire des enfants est un choix, ils ne sont pas responsables de leur empreinte : couches (lavables ou jetables), santé, habits, conso, surface de logement ... Ca compte aussi.
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contact).

**Comment by Clemog** [comment]
Bonjour, 

Merci pour le retour ! Nous répondons à la question dans notre [FAQ](https://nosgestesclimat.fr/questions-frequentes#enfants) :)
