### ISSUE TITLE
Conso de viande et poisson mensuelle

### ISSUE THREAD

**Issue by nosgestesclimat** [incubateur-ademe/nosgestesclimat#2008]
Bonjour, je suis presque végétarienne : je mange de la viande en moyenne une fois tous les 2 mois et du poisson envion 1 à 3 fois pas mois. Je en peux pas compter de manière hebdomadaire ...
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contact).

**Comment by Clemog** [comment]
> Bonjour, je suis presque végétarienne : je mange de la viande en moyenne une fois tous les 2 mois et du poisson envion 1 à 3 fois pas mois. Je en peux pas compter de manière hebdomadaire ...

Bonjour ! 

Bravo pour cette consommation très réduite ! C'est une bonne remarque (lié en partie à #961), on pourrait effectivement aller plus loin sur le choix de fréquence. Pour le moment, vous pouvez choisir de ne pas prendre en compte ces quelques repas avec viande.
