### ISSUE TITLE
Retours [Meta Loisirs] Culture 

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [incubateur-ademe/nosgestesclimat#2022]
Désolé j'arrive après le merged de #1959 mais difficile de répondre toujours dans les temps.

De toute façon pas beaucoup de chose à dire sauf un sujet d'importance (en bas de message). **C'est top en tout cas je trouve pour une première version !**

### Retours mineurs
- On trouve l205 `* 0.04 * (0.25 + 0.12)`. J'imagine qu'il s'agit de ratio de CA mais ne faudrait-il pas mettre ça dans des variables ?
- Même remarque l86 avec le `* 0.9`. J'imagine que c'est le ratio 59.2/59, non ?
- **Musée** : j'ai tiqué sur le terme "fréquence pondérée" qui est en réalité approximée. La pondération pour moi c'est en réalité la division que tu fais par la proportion de visiteurs.
- **Instrument de musique** : je comprends le dilemme d'attribuer le code C.32 (instrument de musique) aux détenteurs d'instruments car le code correspond aux émissions actuelles là ou la détention d'instrument de musique peut être vieille. Mais j'ai pas d'autres solutions que poser la question de l'achat cette année, ce qui ne vaut pas le coup pour 3 kgCO2e + Cf. deuxième partie du message.
- **Édition** : un petit détail mais si la dépense moyenne est d'environ 20 euros/an, pourquoi avoir fait le choix d'associer la dépense moyenne à la réponse "autour de 10 euros" ? Cela devrait être "autour de 20 euros" la moyenne, non ? Et autour de 10 euros = coeff 0,5 ; autour de 30 = coeff 1,5 ; + de 30 euros = coeff 3 
- **Pour R90-92** : j'ai demandé au Citepa et il n'est pas possible d'avoir les émissions directes désagrégées. Ça aurait été idéal car notre approche par les ratios de CA surestime je pense très largement la part de R92 dans le code agrégé au regard du volume d'argent brassé.

### Source SDES à mettre à jour
En effet, nos données SDES portent sur l'année 2017 (source 2021). Ces données transmises ne font pas de différences entre consommation des ménages APU (Administration publique) et ISBLM (Institution sans but lucratif au service des ménages), différences que font les données portant sur l'année 2018 (source 2022). A titre d'exemple, les émissions du code R90-92 "portées" par les APU et ISBLM c'est environ 55%, environ 39% pour les J.59-60. **C'est donc très significatif !** Il y a en a même dans le code CPA.31-32 (mais très certainement beaucoup plus lié à l’achat de meuble pour les administrations que à l'achat d'instrument même si il doit y avoir une petite part liée aux achats des orchestres nationaux/militaires, etc.)

Je vais ouvrir une issue sur le sujet mais je pense pertinent qu'on se rapproche de ce qu'il a était évoqué lors du GT Empreinte (émissions de GES des APU/ISBLM + services privés qu'on juge essentiel). Je vais essayer de proposer une première version pour voir la différence que cela représente sur les services sociétaux

**Comment by JuliePouliquen** [comment]
Hello @Benjamin-Boisserie-ABC merci pour tes retours !

> * On trouve l205 `* 0.04 * (0.25 + 0.12)`. J'imagine qu'il s'agit de ratio de CA mais ne faudrait-il pas mettre ça dans des variables ?
> 
> * Même remarque l86 avec le `* 0.9`. J'imagine que c'est le ratio 59.2/59, non ?

Bonne remarque. Mes pratiques Publicodes sont encore à améliorer ! Je vais voir pour faire ça.

> * **Musée** : j'ai tiqué sur le terme "fréquence pondérée" qui est en réalité approximée. La pondération pour moi c'est en réalité la division que tu fais par la proportion de visiteurs.

Yes je vais modifier le verbatim.

> * **Instrument de musique** : je comprends le dilemme d'attribuer le code C.32 (instrument de musique) aux détenteurs d'instruments car le code correspond aux émissions actuelles là ou la détention d'instrument de musique peut être vieille. Mais j'ai pas d'autres solutions que poser la question de l'achat cette année, ce qui ne vaut pas le coup pour 3 kgCO2e + Cf. deuxième partie du message.

Tu proposerais de supprimer la pratique de la musique ?

> * **Édition** : un petit détail mais si la dépense moyenne est d'environ 20 euros/an, pourquoi avoir fait le choix d'associer la dépense moyenne à la réponse "autour de 10 euros" ? Cela devrait être "autour de 20 euros" la moyenne, non ? Et autour de 10 euros = coeff 0,5 ; autour de 30 = coeff 1,5 ; + de 30 euros = coeff 3

Oups, si c'est bien ça c'est une erreur. Je vais vérifier et modiifer.

> * **Pour R90-92** : j'ai demandé au Citepa et il n'est pas possible d'avoir les émissions directes désagrégées. Ça aurait été idéal car notre approche par les ratios de CA surestime je pense très largement la part de R92 dans le code agrégé au regard du volume d'argent brassé.

Oui d'où mes emails de fin juillet ;).

> Source SDES à mettre à jour

Je te rejoins, il est important que l'on fasse cette mise à jour ! Pour le coup, je préférerais attendre le retour de @Clemog parce que j'aurais un peu peur de faire des bêtises (et que je pense que j'y passerais 5 fois plus de temps sans son éclairage).
