### ISSUE TITLE
Action "manger de la viande une seule fois par jour" proposée quand on mange déjà moins qu'une fois par jour

### ISSUE THREAD

**Issue by lekda** [incubateur-ademe/nosgestesclimat#2023]
Bonjour, 

## Poser une question

L'action intitulée `manger de la viande une seule fois par jour` correspond en réalité à une action `réduire la viande par deux`.  (voir [l'url de l'action](https://nosgestesclimat.fr/documentation/alimentation/r%C3%A9duire-viande/par-deux) et ce texte qui la décrit [2]).

Une conséquence de ce nommage étrange est qu'on peut propose l'action `manger de la viande une seule fois par jour` à quelqu'un qui mange de la viande trois fois par semaine [1].

Est-ce le comportement normal et attendu ? 

## Proposer une amélioration

Si ça n'est pas le comportement normal, une solution de moindre effort serait de modifier soit le nommage de la règle, soit le nombre de repas carné / semaine pour que ce soit cohérent. 

L'action ayant, je pense, le plus de sens serait de créer deux fiches actions différentes : 
1. Une fiche action `manger de la viande une seule fois par jour` qui serait celle actuelle avec la condition d'applicabilité rehaussée à nombre de plats de viande >7 et dont l'impact serait la différence repas carné - repas VG * le nombre de repas évité.
2. Une seconde fiche action `réduire la viande par deux` qui pourrait être proposée avec les conditions et effets actuels (repas carnés >= 2, impact différence repas carné - repas VG * le nombre de repas évité.)

Il y a un surcout de complexité à l'implémentation de deux cartes plutôt qu'une (et peut être à l'usage?). L'idée étant que se limiter à un repas carné par jour ou diviser par deux sa conso de viandes sont deux actions qui peuvent cibler des personnes à un moment différent de leur parcours d'engagement climatique. 

Amicalement, 
Pierre-Marie

Note : Les solutions proposées pourraient apporter une solution complémentaire à #1197 et #1246 qui soulevaient des problèmes sur cette même action. 

[1] 
![image](https://github.com/incubateur-ademe/nosgestesclimat/assets/26326375/7988085b-92f9-4516-ad82-0b69b8913f79)
L'action m'est proposée alors que je mange moins d'un repas carné par jour : 
{
  "alimentation . plats . poisson 1 . nombre": "1",
  "alimentation . plats . végétarien . nombre": "5",
  "alimentation . plats . végétalien . nombre": "5",
  "alimentation . plats . viande 2 . nombre": "0",
  "alimentation . plats . viande 1 . nombre": "3"
}

[2]  >Remplacez la moitié de vos repas avec de la viande par des repas végétariens.

**Comment by JuliePouliquen** [comment]
Bonjour @lekda,
Merci beaucoup pour ces remarrques très pertinentes, et pour vos investigations ! Nous allons sans doute rajouter cela à notre todo très prochainement.
Julie
