### ISSUE TITLE
Valeurs par défaut pour toutes les questions

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [incubateur-ademe/nosgestesclimat#2025]
En faisant une simulation en répondant "je ne sais pas" à toutes les questions (improbable je sais) je me suis rendu compte que par défaut plusieurs questions se voyaient attribuer "rien". C'est le cas des questions scooter, camping-car/caravane, mode efficace, eau en bouteille, piscine.

Pour de nombreuses autres questions, nous faisons le choix d'attribuer qqch si l'utilisateur répond "je ne sais pas" : des heures de vols, une conso d'énergie représentant la réalité du mix et des consommation en France, etc.

Or en théorie toutes ces réponses "je ne sais pas" correspondent à notre français moyen (qui n'existe pas bien sûr) et on devrait donc attribuer des valeurs (même non entière comme le 0,3 climatiseur par défaut).

C'est un sujet à creuser il me semble  car par exemple en regardant très (très) vite, on voit que :
 - pour les deux roues il y en a 2,7 millions en circulation -> environ 5 % de la population
- pour les campings car : 457 000 -> un peu moins de 2% des foyers
- pour les piscine : 3,2 millions de piscines privées, dont 1,55 million de piscines enterrées et 1,64 million de piscines hors-sol -> 10 % des foyers équipés.
- eau en bouteille : près d'une personne sur deux (48 %) continue de consommer de l'eau en bouteille chaque jour en France

Si j'ai le temps j'essaierai de me pencher dessus mais c'est peut être quelques dizaines (voir une centaine ?) de kgCO2eq manquant à notre valeur moyenne

**Comment by JuliePouliquen** [comment]
À relier à #1907 #1535 #1437
