### ISSUE TITLE
Pertinence de "transport . empreinte" 

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat#2047]
Quel est l'utilité de la règle `transport . empreinte` ? Pourquoi ne pas faire comme les autres catégories et juste utiliser `transport` ?

**Comment by Clemog** [comment]
C'est un hack lié à https://github.com/betagouv/publicodes/discussions/373 :/

**Comment by florianpanchout** [comment]
Il va me falloir une explication de texte

**Comment by jeannelf** [comment]
On doit avoir fait https://github.com/incubateur-ademe/nosgestesclimat/issues/2079 pour travailler sur ca

**Comment by Clemog** [comment]
@florianpanchout c'est bon pour moi ici : https://github.com/incubateur-ademe/nosgestesclimat/pull/2095

Je ne merge pas sur preprod je vois qu'il y a une subtilité côté site avec logement . impact que je ne suis pas sur de bien comprendre mais bien présente.

Sur la refonte c'est également dans certains fichiers gérés par @bjlaa

**Comment by jeannelf** [comment]
rien a tester pour moi ici non @florianpanchout ?
@Clemog on n'avait pas dit que c'était dépendant de #2079 ?

**Comment by Clemog** [comment]
> rien a tester pour moi ici non @florianpanchout ?
> @Clemog on n'avait pas dit que c'était dépendant de #2079 ?

In fine, je pensais que ce serait lié mais pas nécessaire ;)
