### ISSUE TITLE
Diviser directement les différents impacts du logement par le nombre d'habitant

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat#2048]
Pourquoi l'empreinte des différents postes du logement n'est pas directement divisé par le nombre d'habitant ? Ça empêche d'afficher directement l'empreinte individuelle d'une sous catégorie

**Comment by Clemog** [comment]
C'était une simplification au départ, à refondre probablement !

**Comment by jeannelf** [comment]
ça a été inclus dans la refonte ça @florianpanchout ? est-ce qu'on s'en occuperait pas plus tard ?

**Comment by jeannelf** [comment]
Point d'attention : il semblerait qu'aujourd'hui la division par le # d'habitants est faite en dur dans le site, à vérifier, auquel cas on fait juste une branche à part qu'on mergera une fois la refonte faite

**Comment by Clemog** [comment]
@florianpanchout c'est bon pour moi ici : https://github.com/incubateur-ademe/nosgestesclimat/pull/2095

Je ne merge pas sur `preprod` je vois qu'il y a une subtilité côté site avec `logement . impact` que je ne suis pas sur de bien comprendre mais bien présente.

Sur la refonte c'est également dans certains fichiers gérés par @bjlaa


![Image](https://github.com/incubateur-ademe/nosgestesclimat/assets/55186402/fd080db2-7c55-40ca-a1b1-e34950aca411)
