### ISSUE TITLE
Comment pouvoir exporter les donnees pour un traitement personel ?

### ISSUE THREAD

**Issue by pierreblum** [incubateur-ademe/nosgestesclimat#2050]
> ⚠️ Avant de créer une issue, lisez attentivement [notre FAQ](https://nosgestesclimat.fr/questions-frequentes) qui explicite un bon nombre des limites du test nosgestesclimat.fr.

Nous sommes un collectif « bougeons » et nous sommes basés à Bruxelles, Proposer une amélioration. Nous avons l’ambition de proposer un accompagnement aux habitants de notre commune (85 000 habitants) pour réduire leur emprunte de 20 % en 2 ans. Nous accompagnons les personnes de manière individuelle pour le moment et utilisons votre calculateur dans la phase Alpha.

Certaines personnes sont prêtes à partager l’entièreté des données pour que l’accompagnateur fasse une proposition pour réduire de 20 % l’emprunte. Nous m’avons pas trouvé de possibilité de partager les données avec un tiers (et le consentement de la personne). La seule possibilite est d'envoyer l'url (toutes les informations ne s'y trouvent pas)

Quels sont les moyens de partage de données ?
-	Export des données dans un fichier Excel
-	Création d’un rapport en format pdf 

Je vous remercie d'avance
Pierre Blum
+32470801628
pierre.blum@gmail.com

**Comment by JuliePouliquen** [comment]
Bonjour @pierreblum,

Si les utilisateurs laissent leur aresse à la fin de leur simulation, ils reçoivent un email avec un lien vers leur simulation. Ce lien est partageable, et vous permet de voir toutes leurs réponses (sur la page /profil).
Bien à vous,

Julie

**Comment by pierreblum** [comment]
Merci Julie
