### ISSUE TITLE
Choix lectures étrange

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat#2053]
Un peu étrange d'avoir "Moins de 10" et "De 10 à 30" avec "Autour de 10" au milieu non ?

<img width="461" alt="Screenshot 2023-09-01 at 13 01 11" src="https://github.com/incubateur-ademe/nosgestesclimat/assets/8115933/87471e04-2f36-4280-b0a6-a8e9fcdd1ee5">

**Comment by JuliePouliquen** [comment]
> Un peu étrange d'avoir "Moins de 10" et "De 10 à 30" avec "Autour de 10" au milieu non ?
> <img alt="Screenshot 2023-09-01 at 13 01 11" width="461" src="https://user-images.githubusercontent.com/8115933/265003097-87471e04-2f36-4280-b0a6-a8e9fcdd1ee5.png">

![image](https://github.com/incubateur-ademe/nosgestesclimat/assets/4005340/6c0d7e9d-8014-42ac-9fcc-daa68bee20b9)

"Moins de 5" / "Autour de 10" / "De 15 à 30" / "Plus de 30" ?

**Comment by florianpanchout** [comment]
Pourquoi pas juste 
- Moins de 5 €
- De 5 € à 15 €
- De 15 € à 30 €
- Plus de 30 €

(Est-ce que ce n’est pas dommage d'appliquer un ratio monétaire pour les livres alors que l'on a le FE d'un livre ? Les deux derniers livres que j'ai achetés m'ont couté respectivement 2€ et 30€...)
