### ISSUE TITLE
Unité des boissons sucrées manquante 

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat#2055]
L'unité n'est pas définie pour les boissons sucrées : https://github.com/incubateur-ademe/nosgestesclimat/blob/637e8fd82009866a91fc4310bd77f4e53ecee8e0/data/alimentation/alimentation%20.%20boisson.publicodes#L275

**Comment by Clemog** [comment]
Ça fait partie des nombreuses correction de #2014 :)
