### ISSUE TITLE
Il manque l'attribut formule pour la consommation `local . consommation`

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat#2061]
Il manque l'attribut `formule` pour la règle `alimentation . local . consommation`, ce qui fait que publicodes ne renvoie pas un objet `NGCRule` valide par la suite

**Comment by Clemog** [comment]
Hyper intéressant comme coquille merci !

**Comment by Clemog** [comment]
C'est fixé dans la branche de preprod, pas besoin de review pour cet ajout je pense :)
