### ISSUE TITLE
Word not translated in the English version

### ISSUE THREAD

**Issue by Oocedar** [incubateur-ademe/nosgestesclimat#2062]
Hello,
I simply spotted a french word (nuits) not being translated in the English version (nights) of the question regarding HomeExchange vacations.
I believe this is self-explanatory and should quickly be corrected ;)
Have a nice day,
C.

![image](https://github.com/incubateur-ademe/nosgestesclimat/assets/115618939/c65a7355-0bbe-4eea-9847-0a5dc648edb9)

**Comment by Clemog** [comment]
Merci @Oocedar, c'est corrigé !
