### ISSUE TITLE
Consommation électrique de la voiture électrique comptée double

### ISSUE THREAD

**Issue by NicolasHanus** [incubateur-ademe/nosgestesclimat#2070]
> ⚠️ Avant de créer une issue, lisez attentivement [notre FAQ](https://nosgestesclimat.fr/questions-frequentes) qui explicite un bon nombre des limites du test nosgestesclimat.fr.

## Poser une question

_Décrivez ici le problème que vous avez eu, l'amélioration que vous souhaitez proposer, ou toute autre question ici._

## Proposer une amélioration

J'ai une voiture électrique que je recharge majoritairement à mon domicile. Du coup, il me semble que l'impact de sa consommation électrique est comptée deux foid: une fois dans l'impact associé à l'usage de mon véhicule, et une autre fois lorsqu'on me demande la consommation électrique globale de mon logement (rubrique logement / chauffage je crois).

Il serait intéressant de demander si le véhicule électrique est rechargé au domicile (un peu, souvent, tout le temps) afin de pouvoir déduire la partie corresponsante de la facture électrique

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by JuliePouliquen** [comment]
Bonjour Nicolas,

Merci beaucoup pour ce retour. C'est un souci que nou avons bien identifié et que nous devons régler, je me permets de clôturer au profit de https://github.com/incubateur-ademe/nosgestesclimat/issues/1934
Très bonne semaine,

Julie
