### ISSUE TITLE
Mise à plat des valeurs par défaut

### ISSUE THREAD

**Issue by JuliePouliquen** [incubateur-ademe/nosgestesclimat#2074]
Audit + proposition de fonctionnement + implémentation
À ce jour nous n'avons pas le même comportement pour les valeurs par défaut partout dans le simulateur : pour certaines on applique une moyenne française (en moyenne les français vont 0,7 nuits en hôtel - j'invente le chiffre pour la clarté), pour d'autres un "comportement moyen" binaire (typiquement : moto par défaut, non). Pour suivre l'exemple donné on a donc dans l'empreinte par défaut 0,7 empreinte de nuit d'hôtel et 0 empreinte de moto en par défaut : deux approches très différentes et qui font que notre empreinte de départ a des trous.

Liste exhaustive des questions présente [ici](https://nosgestesclimat.fr/questions)

À relier à #1437 #2025 #1535 #1907

**Comment by florianpanchout** [comment]
Si on revient à une valeur arbitraire (comme pour la moto par exemple), donc une valeur par défaut qui serait toujours une réponse possible (par exemple 1 climatiseur au lieu de 0,3), est ce que l'empreinte de départ changerait beaucoup ?

Si non, j'aurais tendance, dans un premier temps, à préférer cette solution, intellectuellement et techniquement plus simple. Il sera toujours temps d'ouvrir un grand débat sur le rôle de cette valeur par défaut par la suite.

**Comment by JuliePouliquen** [comment]
Propositions de modifications : 

- **Alimentation** : 
   - ↗️ Café : 10 par semaine ([500 tasses par français par an](https://fr.statista.com/themes/10144/le-cafe-en-france/#topFacts))
   - ↘️ Thé : 3 par semaine ([250g par français par an](https://www.francesoir.fr/lifestyle-vie-quotidienne/le-boom-de-la-consommation-en-france), à raison de 2g par tasse)
   - ↗️ Chocolat : 1 par semaine (consommation moyenne non trouvée mais non nulle)
   - ↘️ Boissons sucrées : 1L par semaine ([50,9 litres par an par personne](https://www.sante-et-nutrition.com/consommation-soda-france/))
   - ↗️ Alcool : 1,5L par semaine ([79,6 litres par personne et par an](https://www.insee.fr/fr/statistiques/4319377#graphique-figure2))
- **Divers** : 
   - 🤔 Modification de la question "Quels meubles de moins de 10 ans possédez-vous ?" en "Quels sont les meubles que vous avez achetés neufs dans les dix dernières années ?"... quoique dans la première version on inclut la seconde-main du coup ce qui est intéressant... 
      - La liste des meubles fait très "liste base empreinte". J'aurais proposé de basculer l'armoire dans les grands meubles. La présence des mobiliers de jardin est assez anachronique, peut-on également les inclure dans "grands meubles" (en faisant une liste importante de suggestions de grands meubles ?)
      - ↘️ Canapé : 0,83 par foyer sur 10 ans (avec [une grosse incertitude sur la donnée extrapolée à partir d'un CA](https://www.neomag.fr/article/9771/2021-bien-meilleure-annee-que-2020-pour-le-marche-de-lameublement))
      - ↗️ Matelas : 1,3 par foyer ([3,9 millions de matelas par an](https://www.planetoscope.com/Commerce/2030-les-ventes-de-matelas-en-france.html))
      - ↘️ Sommier / lit : 0,82 par foyer (même source que ci-dessus : 2,5 millions de sommiers)
   - Animaux domestiques : 
      - ↘️ Chats : 15 millions soit 0,49 par foyer
      - ↗️ Chien : 7,5 millions soit 0,25 chiens "moyens" par foyer
   - Électroménager : même réflexion que ci-dessus pour la question... [Source de données sur les volumes de vente](https://fr.statista.com/marches/1164/themes/1279/appareils-menagers/).
      - ↘️ Réfrigérateurs : 2,7 millions soit 0,89 par foyer sur 10 ans
      - ❌ Mini-réfrigérateur (fait trop base empreinte : pourquoi pas machine à raclette ou billig ?)
      - ↗️ Congélateurs : 700 000 soit 0,23 par foyer sur 10 ans
      - ↘️ Lave-linge : 2,85 millions soit 0,93 par foyer sur 10 ans
      - ↗️ Sèche-linge : 2,78 millions soit 0,91 par foyer sur 10 ans
      - ↗️ Lave-vaisselle : 2,7 millions soit 0,89 par foyer sur 10 ans
      - ❌ Hotte (renouvellement inférieur)
      - ↘️ Four : 1,2 millions soit 0,39 par foyer sur 10 ans
      - ↘️ Micro-ondes : 2,5 millions soit 0,82 par foyer sur 10 ans
      - ↘️ Plaques : 500 000 soit 0,16 par foyer sur 10 ans
      - ↘️ Bouilloire : 1,95 millions soit 0,64 par foyer sur 10 ans
      - ↗️ Machine à café : 5 millions soit 1,64 par foyer sur 10 ans
      - ↘️ Aspirateur : 2,3 millions soit 0,75 par foyer sur 10 ans
      - ↗️ Robot de cuisine : 1 million soit 0,32 par foyer sur 10 ans
   - Vêtements : en moyenne les français achètent [46 articles par an (pour 430€)](https://fr.fashionnetwork.com/news/Sur-dix-ans-le-nombre-de-vetements-achetes-dans-les-chaines-de-mode-a-bondi-de-33-,1406055.html). Aujourd'hui dans le simulateur nous intégrons moins de la moitié de cette somme (19 articles). Je propose de tout revaloriser : 
      - ↗️ 10 tee-shirts
      - ↗️ 4 pantalons
      - ↗️ 2 shorts
      - ↗️ 3 sweats
      - ↗️ 3 robes
      - ↗️ 3 chemises
      - ↗️ 2 pulls
      - ↗️ 3 paires de chaussures
      - ✅ 1 manteau
      - ↗️ 10 petits articles
      - ↗️ 2 gros articles
   - Numérique : 
      - ↗️ durée journalière : 2,2 h
      - La temporalité de 10 ans me paraît décalée par rapport aux achats numériques (décalage avec les durées de vie). J'aurais baissé à 5 ans.
         - ↗️ Téléphones : 15,7 millions vendus par an soit 1,17 par personne sur 5 ans
         - ✅ Appareil photo : marché en berne, laissons à zéro
         - ❌ Home-cinema : aucune donnée mais ça fait très "base empreinte" comme question => qu'entend-on par "home-cinema" ? Ça comprend écran + son ? Les deux sont dessous. Je propose d'enlever.
         - ↘️ Ordinateurs portables : 2,5 millions vendus par an soit 0,19 par personne sur 5 ans
         - ✅ Ordi fixe : marché en berne, laissons à zéro
         - ✅ Tablette : 56% des foyers en possèdent une. Pas de taux de renouvellement ou de volume d'achat. Laissons à 0 (mais sous-évalué)
         - ↘️ Téléviseur : 4,1 millions vendus par an soit 0,67 par **foyer** sur 5 ans
         - ✅ Vidéo-proj : Pas de volume d'achat. Laissons à 0 (mais sous-évalué)
         - ↗️ Enceinte bluetooth : 2,8 millions vendus par an soit 0,46 par **foyer** sur 5 ans
         - ✅ Enceinte vocale : 3,2 millions d'utilisateurs. Pas de taux de renouvellement ou de volume d'achat. Laissons à 0 (mais sous-évalué)
         - ✅ Montre connectée : Pas de volume d'achat. Laissons à 0 (mais sous-évalué)
         - ↗️ 🤝 Consoles : mettre ensemble consoles de salon et portables (FE moyen). 53% de foyers en ont au moins 1. J'en mettrais 1 pour éviter le sous-équipement.
- Logement : 
   - ↗️ Piscine : si "je sais pas", attribution d'une part des 1,55 millions de piscines enterrées en France (avec surface moyenne de 30 m² - arbitraire)

[Manque le transport - to be continued]
À vos retours !

**Comment by Clemog** [comment]
> **Alimentation** :
> * ↗️ Café : 10 par semaine ([500 tasses par français par an](https://fr.statista.com/themes/10144/le-cafe-en-france/#topFacts))
> * ↘️ Thé : 3 par semaine ([250g par français par an](https://www.francesoir.fr/lifestyle-vie-quotidienne/le-boom-de-la-consommation-en-france), à raison de 2g par tasse)
> * ↗️ Chocolat : 1 par semaine (consommation moyenne non trouvée mais non nulle)
> * ↘️ Boissons sucrées : 1L par semaine ([50,9 litres par an par personne](https://www.sante-et-nutrition.com/consommation-soda-france/))
> * ↗️ Alcool : 1,5L par semaine ([79,6 litres par personne et par an](https://www.insee.fr/fr/statistiques/4319377#graphique-figure2))

Tu as pu reboucler avec les besoins journaliers / empreinte moyenne d'une journée type selon les études mentionnées dans la base empreinte ?

**Comment by Clemog** [comment]
> * La liste des meubles fait très "liste base empreinte". J'aurais proposé de basculer l'armoire dans les grands meubles. La présence des mobiliers de jardin est assez anachronique, peut-on également les inclure dans "grands meubles" (en faisant une liste importante de suggestions de grands meubles ?)

Pour moi c'est une autre question donc un peu annexe à cette issue j'ai l'impression

**Comment by Clemog** [comment]
> * ↗️ Matelas : 1,3 par foyer ([3,9 millions de matelas par an](https://www.planetoscope.com/Commerce/2030-les-ventes-de-matelas-en-france.html))
> * ↘️ Sommier / lit : 0,82 par foyer (même source que ci-dessus : 2,5 millions de sommiers)

Il y aurait 3 matelas sur 10 utilisés sans sommier ?

**Comment by JuliePouliquen** [comment]
> Tu as pu reboucler avec les besoins journaliers / empreinte moyenne d'une journée type selon les études mentionnées dans la base empreinte ?

Au vu des modifs proposées je pense que la journée type est équivalente : légère baisse des boissons sucrées compensée par hausse du chocolat et hausse de l'alcool. Le thé et le café ne représentent pas, il me semble, de réponse à un "besoin journalier". D'un point de vue énergétique les modifications proposées s'équilibrent.

> Pour moi c'est une autre question donc un peu annexe à cette issue j'ai l'impression

C'est pas faux, je laisse cette question de côté et vais créer une nouvelle issue.

> Il y aurait 3 matelas sur 10 utilisés sans sommier ?

Non il y a renouvellement plus fréquente du matelas que du sommier : ce sont les achats sur 10 ans (ce qui semble logique). Il s'agit je pense de revoir l'intitulé de la question : est-ce qu'on nous demande de renseigner les meubles que l'on possède à la maison, quel que soit leur mode d'achat / fabrication et durée de vie ? Ou les meubles que l'on a achetés neufs dans les 10 dernières années ? C'est très différent (typiquement, chez moi : rien à voir, quasi rien de moins de 10 ans neuf, que de l'occaz et/ou du vieux... mais j'ai bien des lits, tables et chaises !).

**Comment by florianpanchout** [comment]
[Voila ce que ça donnerait côté front si l'on arrondissait les placeholders](https://nosgestesclimat-git-round-default-nos-gestes-climat.vercel.app/). C'est juste visuel donc ça entraine vite des problèmes d'UX (pour le nombre de passager ça affiche 1 mais si je tape 1 ça me met un impact négatif)

**Comment by JuliePouliquen** [comment]
J'extrais de ce sujet les questions du numérique, de l'électroménager et du mobilier qui me semblent mériter une discussion à part.

**Comment by jeannelf** [comment]
@JuliePouliquen @Clemog comment je peux tester à part à revérifier les valeurs en faisant le test ?

**Comment by Clemog** [comment]
Je dirais que ce n'est pas forcément une vérification des valeurs mais plus une vérification que les valeurs sont bien attribuées, que ça ne casse pas les questions ou l'ordre car on touche pas mal à des logiques de mécanismes et ça peut engendrer des bugs sur le site
