### ISSUE TITLE
Gérer le comportement des `référence` / `références`

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat#2077]
Dans le modèle, on utilise parfois les attributs `référence` ou `références` pour indiquer les source des données, mais ces sources sont le plus souvent ajouter dans la `note`.

Plusieurs choses:

- L'attribut `référence` n'existe pas, inutile donc de l'utiliser ! 
- L'attribut `références` permet d'ajouter un bas de bas de la doc les liens intéressants mais le formatage laisse à désirer .. Exemple pour /documentation/bilan

<img width="846" alt="image" src="https://github.com/incubateur-ademe/nosgestesclimat/assets/55186402/d14c9f8c-22af-488d-aeda-e7bc670930da">

J'ai l'impression qu'une référence est généralement liée à un chiffre -> mise à jour du chiffre = mise à jour de la note et donc d'une ref

Je propose ici de ne plus les utiliser mais de conserver un fonctionnement ou l'on indique la source dans la note. C'est un peu arbitraire, qu'en pensez-vous @JuliePouliquen @jeannelf ?

**Comment by jeannelf** [comment]
Oui en effet cette mise en forme n'est pas très très heureuse ahha.
Alors en soi, ça me va très bien de tout laisser dans les notes, et même mieux dans le contexte qu'en dehors. 
En revanche petite question : y a t il un moment où on aurait besoin de lister toutes nos références ? pour de la presse ou quoi ? Si non, go pour tout mettre dans les notes et arrêter d'utiliser cet attribut

**Comment by Clemog** [comment]
> En revanche petite question : y a t il un moment où on aurait besoin de lister toutes nos références ? pour de la presse ou quoi ?

Je ne pense pas

**Comment by Clemog** [comment]
> Et pour la gestion de l'historique, on pourrait presque supprimer l'attribut si elles sont deja toutes dans notes les ref

Pas sur de comprendre ?

**Comment by jeannelf** [comment]
> > Et pour la gestion de l'historique, on pourrait presque supprimer l'attribut si elles sont deja toutes dans notes les ref
> 
> Pas sur de comprendre ?

la question est : que fait on de ce qu'il y a aujourd'hui dans `references` : 
je me disais qu'il pourrait etre pertinent de carrément supprimer le champs en base si on le l'utilise plus
mais pour ne pas pas perdre l'historique, on pourrait juste ajouter les liens actuels de `references` à la fin des Notes (ou on va maintenant mettre les liens donc ?) s'ils n'y sont pas

Mais pas grave ou urgent au pire on laisse cest juste histoire d'en profiter pour nettoyer vu que c'st le theme ahah

**Comment by Clemog** [comment]
Cette issue était passée à la trappe dans notre ménage de printemps :)

**Comment by jeannelf** [comment]
oh yes encore du nettoyage ! merci !
