### ISSUE TITLE
Revoir et gérer l'arborescence des fichiers, l'ordre d'écriture des règles

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat#2079]
Cf https://www.notion.so/accelerateur-transition-ecologique-ademe/Charte-du-mod-le-c10791d4fcf54a13826e49dd59297366?pvs=4#9b4ccc8aab9f42938390b8eaa32b2f06

**Comment by jeannelf** [comment]
@Clemog je peux aider sur de la recette ici ? je sais pas trop quoi regarder, mais c'est certianement plus pour @JuliePouliquen ?

**Comment by JuliePouliquen** [comment]
> @Clemog je peux aider sur de la recette ici ? je sais pas trop quoi regarder, mais c'est certianement plus pour @JuliePouliquen ?

Hello @jeannelf c'est moi qui ai fait le travail à l'origine et Clément qui a vérifié. 
J'aimerais bien que l'on mette en place des process et tests pour améliorer le recettage du modèle mais j'avoue que je ne saurais pas bien comment m'y prendre !

**Comment by Clemog** [comment]
On peut se faire un point sur nos tests modèle si tu veux

**Comment by jeannelf** [comment]
avec plaisir, la semaine prochaine de toute facon je suis super chaude pour que vous me briefiez sur le modele et la question du test viendra naturellement apres
