### ISSUE TITLE
Action "Rénover mon logement" _ Détail du ratio 39 %

### ISSUE THREAD

**Issue by AdrienMarty0** [incubateur-ademe/nosgestesclimat#2100]
Bonjour,

Je développe une app mobile pour que chaque citoyen puisse mesurer au quotidien l'impact environnemental de ses écogestes et je vais y intégrer le simulateur NGC. 

Pour l'action "rénover mon logement", je vois que vous utilisez le ratio de 39% de gains énergétiques moyen après rénovation et que ce ratio s'applique donc ensuite sur les dépenses énergétiques liées au chauffage de l'air. 

Dans un soucis d'apporter aux utilisateurs de l'application un outil qui s'approche au mieux de leur réalité, je pense intéressant qu'ils puissent sélectionner le type de rénovation qu'il ont effectué (isolation ou changement des portes et huisseries / isolation des murs / sous-sol / Toiture / combles etc) et y visualiser en ordre d'idée les impacts générés. 

Il est globalement peu commun d'effectuer la rénovation complète de son logement "d'un seul coup" et de ce que je comprends les 39% représentent une moyenne de l'ensemble de ces rénovations.

Ma question est la suivante, connaissons-nous en ordre de grandeur, le ratio de gains énergétiques moyen que l'on pourrait attribuer au différents types de rénovations cités précédemment ? 

Merci par avance,

Adrien Marty

**Comment by JuliePouliquen** [comment]
Bonjour Adrien,

Merci beaucoup pour votre message ! Pouvons-nous vous demander quelle sera cette app mobile ? Ou de nous tenir au courant du lancement ?

Pour le gain énergétique suite à la rénovation, nous nous appuyons sur les chiffres de l'ANAH, évalués à l'occasion du programme "Habiter mieux". Je vois sur [ce document](https://www.calameo.com/read/00358825452c2d75f09f5) que nous pourrions mettre à jour ce chiffre pour 42%. En moyenne, il est indiqué que 3,1 gestes sont réalisés à l'occasion des travaux de rénovation. Néanmoins, il serait sûrement assez abusif de se dire que chacun d'eux améliore de 42% / 3,1 soit ~14% de gain énergétique par action car elles doivent avoir des impacts très différents. 

À ce jour, je n'ai pas de meilleure source à vous proposer !

Bien à vous,

Julie

**Comment by AdrienMarty0** [comment]
Bonjour Julie, 

D'accord, merci pour ce retour. Je vais donc me contenter de ce ratio pour le moment et voir comment je peux le prendre en compte au mieux.

A bientôt,

Adrien
