### ISSUE TITLE
Syntaxe dissidente pour l'estimation via le cout des granulés de bois

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat#2110]
Pour toutes les autres questions on a : `nom_de_la_question_sans_consommation . estimation via le coût`

Alors que pour les granulés de bois on a `logement . chauffage . bois . type . granulés . consommation . estimation via le coût:` donc avec consommation en plus (sans l'indiquer dans le nom de l'aide).

Est-ce qu'il y a une raison à ça ? Et si non, est-il possible de changer pour `logement . chauffage . bois . type . granulés . estimation via le coût`

**Comment by Clemog** [comment]
Non effectivement c'est étrange

**Comment by jeannelf** [comment]
je crée dans GH

**Comment by Clemog** [comment]
Ah non bizarre mais je peux corriger aussi dans #2118
