### ISSUE TITLE
Preprod / Affichage de questions non applicables

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat#2111]
On a un pb dans l'algo du formulaire car certaines questions apparaissent alors qu'elles ne devraient pas

Pour reproduire : Je réponds à "oui" à la question "Utilisez-vous majoritairement la même voiture pour vous déplacer ?", je réponds ensuite à la question carburant puis décide de revenir pour répondre à "non" à la question "Utilisez-vous majoritairement la même voiture pour vous déplacer ?", on revient ensuite à la question du type de véhicule qui ne devrait pas s'afficher..

C'est le cas aussi pour l'avion (plus généralement pour toutes les questions qui dépendent d'un booléen), cf commentaires plus bas

![Kapture 2023-10-16 at 15 47 40](https://github.com/incubateur-ademe/nosgestesclimat/assets/55186402/91e6b4b7-a018-472f-97be-823b5d4baf95)

Est ce que c'est à gérer côté publicodes ? Devrait -on éviter l'usage de "applicable si" au sein des règles de bilan ?

Il me semble que l'idée de base de ces conditions d'applicabilité étaient de permettre de désactiver une branche "entière" du modèle et donc de ne pas faire de calcul dessus si le parent est non applicable. Super le papier c'est plutôt intéressant niveau logique et perf
Mais aujourd'hui dans NGC (et "à cause" des actions), on aurait besoin d'avoir accès à toutes les règles !

**Comment by Clemog** [comment]
@florianpanchout je me demande si c'est pas une erreur liée à l'algo du formulaire ? Je comprends pas pourquoi la question du type s'affiche après suivant puis ne s'affiche plus au refresh..

**Comment by Clemog** [comment]
Tu sais comment c'était géré précédemment ?

**Comment by Clemog** [comment]
Je pense que rajouter une info côté Publicodes n'est pas forcément une bonne idée, j'ai l'impression que la différence, c'est que "prenez vous l'avion" est une `missing variable` de bilan alors que "km en court courrier" ne l'est pas non ?

**Comment by florianpanchout** [comment]
Avant le bouton suivant amenait forcement sur une question non répondu, donc c'était moins visible. Mais sinon ce n'était pas plus géré (il suffisait ensuite de revenir en arrière pour avoir des questions qui ne fonctionne plus)

**Comment by Clemog** [comment]
Là, la question de l'utilisateur régulier est une missing variable de bilan
Je me souviens que j'avais justement un souci d'affichage au moment ou j'ai écrit la question, c'était peut etre lié donc il y a peut etre des conditions d'applicabilité à remettre ou enlever

**Comment by florianpanchout** [comment]
> "prenez vous l'avion" est une missing variable de bilan alors que "km en court courrier" ne l'est pas non ?

Quand on répond "non" à "prenez vous l'avion ?" les deux disparaissent des missing variables de bilan. Hors une des deux seulement doit continuer à être affichée

**Comment by Clemog** [comment]
> Quand on répond "non" à "prenez vous l'avion ?" les deux disparaissent des missing variables de bilan. Hors une des deux seulement doit continuer à être affichée

La différence c'est que "prenez vous l'avions" est une missing variable de bilan par défaut ? Et qu'elle a été répondue

**Comment by Clemog** [comment]
Je crois que c'est la discussion qu'on avait eu la dernière fois 😅

**Comment by Clemog** [comment]
Nope j'ai l'impression que c'est bien ça

On a un souci avec les règles d'applicabilité qui désactivent l'ensemble de la branche et donc `avion . présent` (d'ou le faire d'avoir des `. empreinte` parfois ou se situe la condition d'applicabilité

**Comment by bjlaa** [comment]
Est-ce que ça ne vaudrait pas le coup d'extraire ces règles dans un bloc à part `transport . usager` avec en enfant `transport . usager . avion`, `transport . usager . voiture` ect ? J'ai l'impression que le `. empreinte` fonctionne mais n'est pas forcément clair et relève plus du hack ? Je me trompe peut-être je n'ai pas l'historique 🤔

**Comment by Clemog** [comment]
C'est intéressant yes ! Peut etre qu'on n'a même pas besoin d'aller jusqu'à créer un espace nom `transport . usager` mais on pourrait avoir `transport . usager avion` qui reste dans le fichier `avion`

**Comment by Clemog** [comment]
Mais du coup, pas sur que ça résolve l'issue initiale, tu as commencé qque chose @florianpanchout ou j'essaie de regarder aussi ?

**Comment by bjlaa** [comment]
> Si on fait précédent et que l'on répond non à la question "Prenez vous l'avion", elle devient non applicable ainsi que la question "km court courrier" (puisque leur parent "avion" devient non applicable)

Oui pourquoi pas ! Mon idée était de créer un procédé généralisable si le problème se pose ailleurs - la voiture par exemple - plutôt que de créer une exception dans le modèle.

**Comment by Clemog** [comment]
> Ainsi on a deux questions indiférenciables (puisque toutes les 2 dans les foldedSteps, pas dans les missing variables et non applicables), hors une des deux seulement doit être affichée.

Le bouton précédent ne devrait pas "unfolder" la question sur laquelle on était ?

**Comment by florianpanchout** [comment]
Si on "unfold" une question à laquelle on a répondu on la perd et on ne peut plus l'afficher (vu qu'elle n'est ni dans les folded steps, ni dans les missing variables). Et ce, peut importe que l'on souhaite réellement l'afficher ou non.

Est-ce que la solution la plus propre ne se trouve pas côté modèle ? En laissant applicables les règles qui doivent continuer à s'afficher ?

**Comment by Clemog** [comment]
> Si on "unfold" une question à laquelle on a répondu on la perd et on ne peut plus l'afficher (vu qu'elle n'est ni dans les folded steps, ni dans les missing variables).

Pourquoi, on devrait la récupérer via la liste des questions ? C'est la prochaine dans l'index

**Comment by florianpanchout** [comment]
Je ne suis pas sur de comprendre ? La liste des questions est composée de la concaténation des folded steps et des missing variables

**Comment by Clemog** [comment]
Je teste une branche avec les conditions d'applicabilité revues pour les questions qui "doivent" s'afficher dans tous les cas :)

**Comment by Clemog** [comment]
@florianpanchout est ce que tu peux tester avec cette nouvelle branche : https://github.com/incubateur-ademe/nosgestesclimat/pull/2117

Normalement, j'ai modifié le modèle pour faire en sorte que la question booléenne ne soit jamais `non applicable` comme vous lez suggériez

**Comment by bjlaa** [comment]
Je viens de tester de mon côté ça m'a l'air déjà mieux ! On n'a plus que les questions déjà répondues qui s'affichent avec une valeur bloquée à zéro quand on a répondu Non (dans le cas de l'avion avec les trajets courts par exemple)

**Comment by Clemog** [comment]
Cool ! A mon avis y a juste à tester en enlevant le hack sur l'affichage des questions booléennes meme non applicables ;)

**Comment by florianpanchout** [comment]
Plusieurs infos en vrac : 
- Le paramètre PR dans l'url n'est pas toujours pris en compte (en gros si on arrive directement sur /simulateur/bilan ça prend preprod plutôt que la PR. Si on arrive depuis la home ça prend bien la PR). Autant vous dire que j'étais un peu perdu pour tester
- Il y a un paramètre `isNullable` dans l'évaluation de la règle qui fait exactement ce que l'on attend (il est `true` pour les règles qui ne doivent plus s'afficher, `false` ou `undefined` pour celles qui doivent s'afficher). [Vous pouvez tester ici](https://nosgestesclimat-git-2111-nos-gestes-climat.vercel.app)
- La PR modèle #2117 ne règle donc plus rien (mais impacte l'ordre des questions)

@jeannelf vu le peu de changement niveau code pour arriver à corriger ce bug (qui impacte un nombre non négligeable d'utilisateurs), je conseille de le passer en prod le plus tôt possible

**Comment by Clemog** [comment]
> * La PR modèle [Fix conditions applicabilité #2117](https://github.com/incubateur-ademe/nosgestesclimat/pull/2117) ne règle donc plus rien (mais impacte l'ordre des questions)

Ok, on ferme donc #2117
