### ISSUE TITLE
`check-rules` devrait supprimer les attributs traduits qui ne sont plus dans le modèle

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat#2119]
Le script supprime déjà les règles traduites qui ne sont plus dans le modèle, on pourrait aller un cran plus loin (ping @EmileRolley)

**Comment by jeannelf** [comment]
@Clemog tjs d'actu?

**Comment by Clemog** [comment]
C'est bon désormais ;)
