### ISSUE TITLE
Valeurs par défaut: Transport Vacances / activation du Van ?

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat#2123]
L'attribution d'une valeur par défaut (pourtant existante) pour la caravane et camping pose pb, nous gardons la valeur par défaut pour `transport . vacances` à "non" pour des raison de complexité:
- L'empreinte est divisée entre 2 catégorie : nous ne pouvons appliqué le même comportement / contournement que pour la mosaïque "chauffage" par exemple.
- L'empreinte par défaut est relativement faible au vu des proportions d'usagers de ces véhicules

Néanmoins, ce n'est pas la logique présente dans le reste du modèle..

On pourrait aussi remettre en question le fait d'attribuer une partie de l'empreinte au logement, ce qui complexifie le modèle / site pour peu de cas à priori (à vérifier)

## Van en bonus ?

Introduire une estimation de l'empreinte du van sur la base du camping car / VUL ? -> A décider ça date ce fameux "Bientôt Disponible", on pourrait au moins proposer une estimation grosse maille.

**Comment by JuliePouliquen** [comment]
Du coup pour la scission des impacts, c'est déjà réglé non @Clemog ?
