### ISSUE TITLE
Surestimation de l'impact au kilomètre d'un SUV électrique ?

### ISSUE THREAD

**Issue by mquandalle** [incubateur-ademe/nosgestesclimat#2126]
Le facteur d'empreinte utilisé pour un SUV électrique est de 0,0273 kgCO2e/km : 

https://github.com/incubateur-ademe/nosgestesclimat/blob/11188e80ed6e554cb4ee6da92cd61844780428bd/data/transport/voiture.publicodes#L272-L286

La consommation des véhicules électriques est souvent mesurée en kWh/100km (par analogie avec les "litres au 100" des véhicules thermiques). Calculons la consommation correspondante au facteur d'empreinte utilisé.

Pour l'empreinte du mix électrique, j'utilise la valeur de l'année 2022 sur electricitymaps : 90 gCO2e/kWh (année défavorable, on était plutôt à 60g/kWh avant)

Ce qui donne : 

> 100km * 0,0274 kgCO2e/km / 90gCO2e/kWh = **39 kWh/100km**

On peut aussi ajouter un facteur "efficacité de la charge du véhicule" avec 5 à 10% de perte avec les cables de type 2 majoritairement utilisés. Mais encore une fois le facteur d'émission utilisé pour l'électricité est plutôt défavorable par rapport au mix électrique français historique, et le calcul donnera une consommation au kilomètre plus grande si on prend un mix électrique moins carboné.

Le SUV électrique le plus vendu en France est le Model Y de Tesla. Sa consommation est à 15,7 kWh/100km en norme WLTP. Les tests peuvent monter à 20 kWh sur autoroute, 25 kWh l'hiver. C'est certes un véhicule plus efficient que ses concurrents mais la valeur de 39 kWh/100km me semble très surévaluée pour la consommation moyenne d'un SUV ou d'une berline électrique. Je rate quelque chose ?

Dans tous les cas il me semble utile de décomposer le terme `kgCO2e/km` en `kgCO2e/kWh` et `kWh/km` dans le modèle publicodes.

**Comment by mquandalle** [comment]
Je refais le calcul avec le facteur 2023 sur electricitymaps : 51 gCO2e/kWh

> 100km * 0,0273 kgCO2e/km / 51 gCO2e/kWh = 54 kWh/100km

54 kWh/100km, c'est très largement au dessus de la consommation normale d'un SUV électrique.

Effets supplémentaires que l'on pourrait considérer : 
- perte d'énergie à la recharge 
- voitures électrique majoritairement chargées à domicile, majoritairement en heures creuses, donc probablement avec un mix énergétique plus favorable que la moyenne

**Comment by Clemog** [comment]
Les chiffres que nous utilisons actuellement sont ceux de la BE, j'essaie de voir en interne ADEME pour avoir des explications

**Comment by mquandalle** [comment]
Pour insister : actuellement sur NGC, toutes choses égales par ailleurs, la berline thermique est à 1,3x l'empreinte de la berline électrique : 

![image](https://github.com/incubateur-ademe/nosgestesclimat/assets/1730702/6e0bb233-1649-42ee-82dc-9ca968911969)
![image](https://github.com/incubateur-ademe/nosgestesclimat/assets/1730702/098c1155-d795-43b9-8ab0-9b50bca22b11)

Or les études donnent systématiquement un rapport d'au moins x2 sur l'ensemble du cycle de vie pour le véhicule électrique https://bonpote.com/la-voiture-electrique-solution-ideale-pour-le-climat/. Il faut que l'on puisse retrouver cet ordre de grandeur quelques soient les paramètres et le modèle utilisé.
