### ISSUE TITLE
Overflow sur la part de biogaz

### ISSUE THREAD

**Issue by SuperFola** [incubateur-ademe/nosgestesclimat#2128]
> ⚠️ Avant de créer une issue, lisez attentivement [notre FAQ](https://nosgestesclimat.fr/questions-frequentes) qui explicite un bon nombre des limites du test nosgestesclimat.fr.

## Poser une question

J'ai renseigné utiliser du biogaz et ai mis 100 (pensant que cela représenterait 100%), comme mon contrat gaz l'indique. Je partait de 7 tonnes CO2/an et je me suis retrouvé à 49. Pourtant je vois bien une soustraction en kgCO2 dans le détail (graphe du bas). Après avoir expérimenté avec, j'ai l'impression que:
- on doit entrer un pourcentage entre 0 et 1 et non 0 et 100
- que le résumé en haut de la page n'accepte pas les valeurs négatives (est-ce possible d'atteindre un résultat comme -49 tonnes CO2/an?)

## Proposer une amélioration

- borner le pourcentage entré par l'utilisateur

**Comment by Clemog** [comment]
Bonjour, effectivement, merci pour le retour ! Nous allons corriger ça très vite ;)
