### ISSUE TITLE
Contribution du biogaz

### ISSUE THREAD

**Issue by ebis06** [incubateur-ademe/nosgestesclimat#2129]
Quelle est la part de biogaz garantie par votre contrat de gaz ?

La formule s'attends à une valeur comprise entre 0 et 1, alors que la plupart des utilisateurs vont rentrer un pourcentage (entre 0 et 100). Toute valeur supérieure à 1 va générer un résultat négatif qui semble complètement fausser la suite des résultats.

Il faudrait:
- Modifier la formule pour qu'elle prenne en compte des pourcentages. 
- Ajouter des garde-fous afin de ne jamais retourner de valeurs negatives ou qui pourraient entrainer des résultats incohérents (tels que 200+ tonnes pour une personne !) .
- Clarifier la question.

Merci!
-Eric

**Comment by Clemog** [comment]
Bonjour, effectivement, merci pour le retour ! Nous allons corriger ça très vite ;)
