### ISSUE TITLE
Bug contrat bio gaz

### ISSUE THREAD

**Issue by Saokin** [incubateur-ademe/nosgestesclimat#2135]
Lorsque je remplie la partie gaz, mon compteur CO2 logement passe en négatif en ajoutant mon contrat 100% gaz vert. Cela empêche ensuite les résultats d'être correctement affichés.

J'ai remplie gaz vert: Oui
taux de gaz vert: 100
Consommation annuelle de gaz: 1736kWh

**Comment by JuliePouliquen** [comment]
Bonjour @Saokin,

Merci du retour !
Je n'ai pas le même souci de mon côté. Mais nous avons récemment mis en ligne une nouvelle version du site. Peut-être êtes-vous tombé sur un bug temporaire ? Voulez-vous réessayer ?

Julie
