### ISSUE TITLE
Distance parcourue en voiture non prise en compte

### ISSUE THREAD

**Issue by sangliersanglier** [incubateur-ademe/nosgestesclimat#2146]
> ⚠️ Avant de créer une issue, lisez attentivement [notre FAQ](https://nosgestesclimat.fr/questions-frequentes) qui explicite un bon nombre des limites du test nosgestesclimat.fr.

## Poser une question

Bonjour,
Je suis étonné de voir que la distance parcourue en voiture n'est pas comptabilisée alors que la consommation de la voiture par kilomètre l'est.
Je ne sais pas si c'est uniquement dû à ce paramètre là mais l'an dernier j'étais à moins de 4,5 tonnes par an (il me semble que la distance annuelle en voiture était demandée) et là je suis quasiment à 6 tonnes/an sans qu'il n'y ait de différence notable dans mon mode de vie.

Sinon l'outil est top et surtout très utile.
Merci d'avance pour votre retour.
Bonne continuation

## Proposer une amélioration

Prendre en compte la distance parcourue en voiture par an. D'autant plus que c'est une donnée facile à renseigner.

**Comment by JuliePouliquen** [comment]
Bonjour... sanglier ?

Je suis désolée de cette expérience, je pense que vous êtes tombé⋅e sur un bug. Pouvez-vous retenter ? Il s'agit, en théorie, de la première question.
Bonne journée,

Julie

**Comment by sangliersanglier** [comment]
Bonjour,
Effectivement, j'ai refait et il y avait bien cette question.
Merci
Cordialement

Le 7 novembre 2023 14:07:22 GMT+01:00, JuliePouliquen ***@***.***> a écrit :
