### ISSUE TITLE
2 tonnes techniquement inatteignables

### ISSUE THREAD

**Issue by PASCCHAP** [incubateur-ademe/nosgestesclimat#2149]
Bonjour,
J'ai fait mon bilan carbone sur le site de l'Ademe, puis je l'ai refait comme si je n'utilisais aucun moyen de transport, manger végétalien, n'avais aucun bien de moins de 10 ans, n'achetais aucun vêtement, ne consommais aucune électricité, n'aller pas sur internet, etc... or je suis quand même arrivée à un total de 2,4T comme s'il était impossible malgré tous les efforts consentis d'arriver à 2T. Donc je ne comprends pas ce résultat.
cordialement

**Comment by JuliePouliquen** [comment]
Je me permets de clôturer cette issue au profit de #2004.
