### ISSUE TITLE
Erreur 500 sur l'ajout d'un membre à un groupe

### ISSUE THREAD

**Issue by clementh44** [incubateur-ademe/nosgestesclimat#2176]
J'ai créé un groupe le 16 septembre suite à mon évaluation.
Aujourd'hui, le lien "amis/resultats" me redirige directement vers "amis/invitation" et quand je veut rajouter une personne, j'ai une erreur 500 sur le lien https://nosgestesclimat.osc-fr1.scalingo.io/group/add-member
Un bug temporaire ? Un groupe trop vieux ?
Merci 👍

**Comment by jeannelf** [comment]
Bonjour Clément, 

Sur quel site avez-vous créé le groupe ? Je vois que le lien que vous partagez est [https://nosgestesclimat.osc-fr1.scalingo.io](https://nosgestesclimat.osc-fr1.scalingo.io/group/add-member) mais le lien du site en producction de Nos Gestes Climat est https://nosgestesclimat.fr/
Avez vous essayé ici, depuis la rubrique Amis ? Ici de notre côté nous n'avons pas pu reproduire d'erreur 500

Bonne journée !

**Comment by clementh44** [comment]
Bonjour,
j'étais bien sur le site en prod. Ce lien viens de la console de mon navigateur. Je viens de réessayer à l'instant et ça fonctionne correctement. Peut-être un problème temporaire 🤔
Merci
