### ISSUE TITLE
Impossible de lancer le quick doc avec le modèle nos gestes climat

### ISSUE THREAD

**Issue by RomainCrevecoeur** [incubateur-ademe/nosgestesclimat#2368]
## Poser une question

J'ai suivi les information du Readme pour lancer le quick doc nos gestes climat dans la dernière version actuelle 2.2.0 mais j'ai une erreur quand je lance le script :  `    "compile:migration": "node scripts/migrationToJSON.mjs" `
![image](https://github.com/incubateur-ademe/nosgestesclimat/assets/162474058/ae406a85-1bd3-4c8c-9845-c69d4240a689)

Est ce que vous avez une piste pour corriger cette erreur ? (j'ai aussi tenté de cloner à nouveau le projet et d'installer les dépendances avec bun)

**Comment by RomainCrevecoeur** [comment]
Cela fonctionne sur un autre ordinateur donc c'est de mon côté. Je creuse...

**Comment by EmileRolley** [comment]
Salut @RomainCrevecoeur, visiblement tu es sur windows. Je me demande si le problème ne vient pas de là avec une mauvaise gestion des chemins des fichiers de notre côté. Est-ce que ton autre machine (sur laquelle ça fonctionne) est sur windows également ?

Normalement, tu n'as pas à utiliser `bun` pour gérer les dépendances mais `yarn`. `bun` est uniquement utilisé comme runtime pour le serveur de dev.

**Comment by RomainCrevecoeur** [comment]
Oui je suis sur windows. Cela fonctionne sur l'ordinateur de Benjamin avec la même version de Windows.

J'avais juste testé de lancer les dépendances via bun mais je suis de nouveau sur yarn.
Le problème est bien un problème de path mais nous n'avons pour l'instant pas trouvé la solution. Cela fait peu de temps que bun est supporté par windows. Je pense que je vais plutôt ouvrir une demande côté Bun et fermer cet issue. 
D'ici à ce qu'on trouve une solution on va peut être s'orienter vers un  WSL linux pour faire fonctionner quick doc

**Comment by Clemog** [comment]
Tu as pu résoudre le souci ?

**Comment by RomainCrevecoeur** [comment]
Ah si c'est résolu de mon côté en prenant la branche preprod
J'avais le pb sur la 2.2.0
