### ISSUE TITLE
Plein de retours sur le forum des Shifters

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat#68]
J'y ai fait une annonce pour tester la beta, et il y a une dizaine de retours très intéressants (dont certains ont aussi été entrés comme des issues)

https://forum.theshifters.org/t/nos-gestes-climat-calculateur-dempreinte-climat-personnelle/2893/11

**Comment by laem** [comment]
J'ajoute un autre retour ici :

> Pas de problème sur l'UX. A part forcément que c'est pas facile de répondre aux questions. On aurait (moi et un ami qui a testé aussi) apprécié à la fin d'avoir des conseils "adaptés" pour réduire notre empreinte. Des trucs superficiels du style "vous pouvez supprimer un Paris<-> New York par an pour diminuer de X tonnes" ou plus précis comme "Voici une liste de banques / fonds responsables"

**Comment by JuliePouliquen** [comment]
Me paraît obsolète.
