### ISSUE TITLE
Amortissement trop sévère pour les appareils numériques

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#849]
La formule qui prend en compte l'âge de l'appareil fait que l'empreinte carbone est payée deux fois en 10 ans:
1/2+1/3+1/4+1/5+1/6+1/7+1/8+1/9+1/10=2 environ
on pourrait mettre une formule qui considère 0 kCO2e après 3 ans car 1/(1+1)+1/(1+2)+1/(1+3)=1.08 et prévenir qu'il ne faut pas renseigner un chiffre inférieur à 1 an

**Comment by laem** [comment]
Merci, très bonne remarque ! On doit revoir complètement le sujet de l'amortissement. Il est crucial. 
On l'a traité pour la voiture, il faut qu'on valide ce choix et qu'on l'étende.

Mais je pense qu'au fond, la seule façon de traiter correctement l'amortissement, c'est de proposer plusieurs mailles de simulation. 1 an, 10 ans, 30 ans.

**Comment by laem** [comment]
Voir #816
