### ISSUE TITLE
Questionnaire plus complet sur la voiture / moto

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#856]
possédez-vous une voiture ?

        quel type ?

        quel kilométrage par an en tant que conducteur ?

    est-ce que vous êtes utilisateur d'autopartage ?

        combien de kilomètres par an en tant que conducteur ?

        si vous possédez une voiture personnelle, est-ce que vous la laissez à disposition à travers un réseau d'autopartage (Drivy/OuiCar...) ?

    combien de kilomètres parcourez vous en voiture en tant que passager (covoiturage, le conducteur est votre conjoint...)

et après si tu veux :

    possédez-vous un deux-roues motorisé ?

        électrique, thermique 2t < 50cc, thermique 4t < 50cc, thermique 4t < 125cc, thermique 4t < 750cc, thermique 4t >= 1000cc

        à quel norme EURO correspond le véhicule ? (sur la carte grise, ou en fonction de l'année ou de la vignette crit'air)

        quel kilométrage ?

D'ailleurs le point sur la norme EURO tu peux l'avoir sur la voiture aussi (ça te permet de donner une idée de la conso, du rejet de particules et de ges...).

et enfin peut-être parler du vélo.

**Comment by laem** [comment]
Quelques infos sur les deux roues ici : https://www.bilans-ges.ademe.fr/documentation/UPLOAD_DOC_FR/index.htm?routier2.htm

**Comment by laem** [comment]
Voir #891

**Comment by JuliePouliquen** [comment]
Obsolète.
