### ISSUE TITLE
Rajout unité chauffage bois et fioul

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [incubateur-ademe/nosgestesclimat#867]
L'unité kWh n'est pas la mieux adaptée pour les chauffage au bois et au fioul
Rajouter les unités : 
  - stère pour la consommation de bois
  - litre pour la consommation de fioul

**Comment by bertrandgorge** [comment]
Attention, pour du chauffage en bois, ce n'est pas en stères mais en tonnes (de granulés). Personne ne chauffe sérieusement avec des buches !

**Comment by bertrandgorge** [comment]
Sachant que les granulés sont à peu près normés, en terme de pouvoir calorifique, mais pas les buches (dépend de la largeur des buches, de leur essence, de leur taux d'humidité).

**Comment by JuliePouliquen** [comment]
Clôturée au profit de #1386
