### ISSUE TITLE
Objectif 2 tonnes : indiquer à quelle échéance

### ISSUE THREAD

**Issue by gaelg** [incubateur-ademe/nosgestesclimat#886]
Le lien "comment ça" ne parle pas vraiment d'objectif 2T/an mais de budget total 100T

**Comment by laem** [comment]
C'est exact, l'objectif de 2 tonnes n'a aucun sens sans scénario précis daté ! C'est ce qu'on explique dans le billet de blog :) 
On va corriger ça !

**Comment by franselectro** [comment]
Bonjour,

Oui un objectif direct à 2t ne parait pas des plus judicieux. Poser un intermédiaire à 4t d'ici 2030 paraitrait déjà un bon échelonnement. 
La notion de budget total est très intéressante mais semble difficile à aborder, peut être à afficher en 2eme couche quand on s'intéresse aux détails.

Les 2t semblent d'autant plus inatteignables à cause du poste "services publics"? Peut être voir pour pouvoir jouer dessus (simuler une décarbonation partielle de ce poste d'ici 2030) et/ou ouvrir une action pour "militer" pour une action carbone dans les services publics.

**Comment by laem** [comment]
> et/ou ouvrir une action pour "militer" pour une action carbone dans les services publics.

Super idée. 

Sur le sujet il y a bien deux points à mon avis : 
- le budget de 2 tonnes par personne est à ma connaissance un objectif x 7 milliards d'humains pour arrêter de déstabiliser le climat. Indépendamment des budgets pour respecter les 1.5° ou 2°, qui sont des compromis : on risque un danger parce qu'on admet qu'en tant que société on n'a pas envie de faire mieux.
- le scénario qui mène à 2t en 2050 / neutralité, qui représente la trajectoire idéale dans le périmètre du compromis ci-dessus incarné par l'accord de Paris

**Comment by laem** [comment]
Voir aussi https://github.com/betagouv/ecolab-climat/pull/109

**Comment by franselectro** [comment]
Je n'ai pas pu trouver l'explication dans le billet de blog.
Mais donc vous êtes en cours sur une approche plus progressive et temporelle de l'objectif?

**Comment by laem** [comment]
Ce n'est pas vraiment dans les priorités : https://github.com/betagouv/ecolab-data/projects/1
Pour l'instant on travaille sur les actions et sur l'amélioration du questionnaire. 
Ainsi que  betagouv/ecolab-climat#109 qui parle de l'écran de fin.
