### ISSUE TITLE
Retours expérience utilisateur

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [incubateur-ademe/nosgestesclimat#893]
Suite au dépilement des issues, voici les retours utilisateurs plus ou moins fréquents (complétés de certaines réflexions personnelles) : 

- [ ] Lorsque l'on clique sur une barre de résultat d’un poste d’émissions avoir un en plus des chiffres un élément visuel et éventuellement rajouter une évaluation en pourcentage des chiffres donnés (cf. image)
![image](https://user-images.githubusercontent.com/66410914/107631243-f2be0180-6c64-11eb-89ad-0e2f10c1790d.png)

- [x] Ajouter une décimale au résultat final (cf. ci-dessous)
![image](https://user-images.githubusercontent.com/66410914/107631537-71b33a00-6c65-11eb-8924-0bee9e58872a.png)

- [ ] Expliquer d’où vient l’impact carbone (#375). Dans ce cas précis, l’utilisateur ne comprenait d’où vient l’impact de la gestion des déchets --> compléter la F.A.Q selon moi
- Répondre à l'affirmation "2 tonnes c'est impossible" #890 --> compléter la F.A.Q 

- [ ] Certains utilisateurs aimeraient pouvoir disposer de sauvegardes/doc récapitulatifs/créer un compte 
             --> suite à nos échanges on abandonne la création d'un compte
             --> réfléchir à un format de restitution/sauvegarde de ses résultats ainsi qu'à un format de suivi (mail, etc.)
 
- [ ] Certains utilisateurs aimeraient lorsque l'on clique sur un choix multiple ne pas avoir à valider le bouton "suivant". L'ergonomie actuelle me convient mais peut être faut-il y réfléchir ?

- [x] Indiquer éventuellement sur la page d’accueil, le temps approximatif pour réaliser la simulation. --> "en 10 minutes"

- [ ] Parfois, plusieurs utilisateurs mettent en avant des difficultés pour modifier les réponses. Faire un travail de vérification sur cette "partie".

- [ ] Donner éventuellement la possibilité de ne faire qu'une partie de la simulation. Cette remarque est faite par les gens qui reviennent plusieurs fois sur NGC. Ex : si je veux faire seulement la simulation de mon impact numérique je dois répondre à toutes les questions précédentes (ou à défaut cliquer je ne sais pas).

- [ ] un détail : essayer de trouver une meilleure formulation que viande 1 et viande 2 (selon moi). Même si elles sont expliquées au moment de la question, quand on navigue dans la partie "modifier mes réponses" les termes viande 1 et 2 apparaissent et ne sont pas parlant.

- [ ] volet alimentation : je trouve bizarre de commencer par la question "Êtes-vous engagé dans une démarche zéro déchet ? ". Je l'aurais mise à la fin et je commencerais par la question sur le petit-déjeuner

**Comment by JuliePouliquen** [comment]
J'ai le sentiment que la plupart des points ci-dessus ont été cochés dans les deux années écoulées. Je me permets de clore.

**Comment by Clemog** [comment]
Le premier point est hyper intéressant, je me permet dans l'ajouter dans https://github.com/incubateur-ademe/nosgestesclimat-site/issues/793
