### ISSUE TITLE
Passer à l'action ne fonctionne pas...

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#899]
Bonjour, Après avoir fait ma simulation, lorsque je clique sur Passer à l'action, la page qui s'ouvre est totalement blanche... désespérant ! 
Je pense que nous ne sommes pas nombreux à faire cette simulation, et si en plus, on n'a pas en fin de test d'idée d'action.... on ne risque pas d'y arriver.

**Comment by laem** [comment]
> Bonjour, Après avoir fait ma simulation, lorsque je clique sur Passer à l'action, la page qui s'ouvre est totalement blanche... désespérant !

Nous allons investiguer, merci pour le retour.

> Je pense que nous ne sommes pas nombreux à faire cette simulation

Si ;) 

> et si en plus, on n'a pas en fin de test d'idée d'action.... on ne risque pas d'y arriver.

Si vous avez déjà complété la simulation, vous avez normalement déjà plein de pistes pour réduire votre empreinte et communiquer dessus :)

**Comment by laem** [comment]
Je n'arrive pas à reproduire. Cela peut-être du à un jeu de réponses en particulier qui déclenchent une erreur sur la page action. 

Si vous voyez ce message, pouvez-vous nous donner le nom de votre navigateur et la version ? 

Peut-être que #176 pourra aider ?
