### ISSUE TITLE
Impact touristique et loisirs

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#906]
Que ce soit hotels, restaurants, loisirs divers, quasi obligatoires à l'etranger, à chaque vacances scolaires etc. On a developpe un desir de voyages et de consommations illimites. Il faudrait developper des plaisirs simples et neutres....autre chose, vous dites manger moins de viande, chauffer moins... mais je le fais depuis longtemps, il faudrait donner des chiffres precis svp. 
Mon impact est de 5 alors que la moyenne est de 11.!! Pour arriver à 2 il faut vivre dans un tonneau ss chauffage ni rien... difficile ma foi!!

**Comment by JuliePouliquen** [comment]
En partie réglé avec la PR hôtellerie. Restent d'autres loisirs à intégrer, qui me semblent bien traités par #1828 et #1776.
