### ISSUE TITLE
Transport & Logement

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#946]
Transport: Dans le questionnaire n'est pas envisagé l'utilisation d'un véhicule électrique Me concernant j'ai deux VE qui sont à 70% rechargés par mon installation Photovoltaïque de 7kWc 

Logement: Dans le questionnaire n'est pas envisagé une maison Passiv Hauf (ossature bois) chauffée par poêle alimenté en granulés bois (coût annuel 100 à 130€ selon la rigueur de l'hiver)

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
> Dans le questionnaire n'est pas envisagé l'utilisation d'un véhicule électrique Me concernant j'ai deux VE qui sont à 70% rechargés par mon installation Photovoltaïque de 7kWc

En effet, on ne peut pas saisir 2 véhicules. Il faut choisir l'un, représentatif de l'usage des autres. Désolé, c'est une question pas simple à cause du partage de véhicules pour le foyer. Nous essaierons de faire mieux.

> rechargés par mon installation Photovoltaïque de 7kWc

Il est je crois peu probable que l'utilisation d'un groupe personnel réduise l'empreinte par rapport au mix français, et si c'est le cas la différence sera mineure. 

>  n'est pas envisagé une maison Passiv Hauf (ossature bois) 

En effet, l'empreinte de la construction ne varie pas encore en fonction du type et l'âge de la maison, ça viendra ! 

> chauffée par poêle alimenté en granulés bois (coût annuel 100 à 130€ selon la rigueur de l'hiver)

Vous pouvez bien préciser un chauffage bois à granulé :)

**Comment by JuliePouliquen** [comment]
Obsolète.
