### ISSUE TITLE
Empreinte de l'internet en fonction des octets plutôt que du nombre d'heure ?

### ISSUE THREAD

**Issue by publicodes** [incubateur-ademe/nosgestesclimat#959]
Bonjour,
Dans le cadre de l'évaluation du numérique, ne faudrait il pas mieux faire un calcul à partir de Mo plus que d'heure sans différencier l'usage?
D'ailleurs je suis à la recherche de données sur l'impact d'un Mo en terme de CO2. J'avais fait une estimation àpartir de la calculette orange mais cette donnée semble très flucuante (j'imagine suivant la politique environnemental du fournisseur et le mode de calcul)

Depuis la page : `https://nosgestesclimat.fr/documentation/numérique/internet/diminuer`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, oui c'est tout à fait vrai. Nous avons simplifié à outrance la question de l'usage de l'internet car la mesure de l'empreinte de l'octet est extrêmement compliquée. Nous avons ajouté à la page de documentation le détail des sources. Les estimations varient très largement, notamment car la notion même de mesure des kWh et encore pire du CO2e/octet est peut-être complètement à côté de la plaque.



https://nosgestesclimat.fr/documentation/numérique/internet/consommation-horaire

**Comment by JuliePouliquen** [comment]
La conso en octet plutôt qu'en heures me paraît une complexification avancée de la saisie. Des avancées ont été faites depuis lors, des expérimentations... je clôture !
