### ISSUE TITLE
Vérifier descriptions et notes

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [incubateur-ademe/nosgestesclimat#974]
En naviguant dans NGC je vois que certaines descriptions ne s'affichent pas et que certaines notes au contraire s'affichent.

Ces notes traduisant nos réflexions devraient être gardées entre nous

**Comment by laem** [comment]
Tu as des exemples ? 
L'objectif des notes est justement de parler des limites ou potentiels de calcul. Ça permet aux gens de savoir où on en est.

**Comment by Benjamin-Boisserie-ABC** [comment]
**1er exemple :**
![image](https://user-images.githubusercontent.com/66410914/114418589-f1e91380-9bb2-11eb-94ca-b345f11b297c.png)
Il me semble qu'il serait plus judicieux de ne pas afficher notre questionnement de la sorte car ça donne à penser qu'on expérimente (même si c'est le cas en partie) et que donc les résultats sont incertains

**2ème exemple :**
![image](https://user-images.githubusercontent.com/66410914/114418949-48eee880-9bb3-11eb-89e1-dc75841f6a82.png)
Idem ici ou l'on peut penser que les estimations sont mauvaises et donc desservir le propos de NGC : même si en effet ce 7% (tiré des guides grand public d'ADEME) mériterait de reposer sur une source mieux chiffrée

**Comment by laem** [comment]
Ces deux notes pourraient être mieux écrites, c'est vrai qu'elles sont assez brutes. Par exemple en précisant : "Voici les limites du calcul actuel et nos pistes pour l'améliorer".

Mais ça me semble quand même important de les garder, pour ces raisons : 
- cette page n'est accessible qu'en deuxième niveau de lecture après avoir cliqué sur le bouton "comprendre le calcul". Je suis d'accord qu'il ne faut pas les afficher hors de la section /documentation réservée à ceux qui font l'effort de creuser
- l'utilisateur qui arrivera sur cette page verra de toutes façons le calcul et pourra constater par lui-même les remarques et limitations que l'on a nous même notés. On lui évite de se dire des choses comme "mais pourquoi on ne me demande pas si je chauffe à 19°C, c'est un bug" ?
- nous avons maintenant fréquemment des retours informés sur notre modèle. Voir par exemple le retour sur l'âge du logement qui nous fournit des statistiques, ou le retour sur le biogaz qui nous fournit des études et chiffres pertinents. Chercher dans nos issues pour trouver l'avancement de notre calcul leur donne une indirection de plus
- je crois que si l'on ne précise pas dans nos propres fiches action les limites de nos sources, on est peut-être en train de reproduire les mêmes erreurs faites dans ces sources qui justement n'ont pas fourni assez d'informations pour remonter au calcul lui-même
- cela nous permet d'enregistrer les limites de nos calculs au plus près du calcul lui-même, plutôt que sur un document séparé ou une issue qu'il faudra garder en tête (mais j'avoue que faire la part entre les deux n'est pas aisé), ainsi que de permettre à google d'indexer plein de textes et mots-clefs sur nosgestesclimat.fr plutôt que sur github.com.

**Comment by JuliePouliquen** [comment]
Obsolète.
